export const teamProfiles = {
  ARI: {
    name: "Arizona Cardinals",
    abbreviation: "ARI",
    gm: "Monti Ossenfort",
    headCoach: "Mike LaFleur",
    offensiveScheme: "Balanced / Spread Concepts",
    defensiveScheme: "Multiple Front",
    window: "Rebuild / Ascending",
    needs: [
      { position: "OT", score: 96, label: "Critical" },
      { position: "EDGE", score: 91, label: "Critical" },
      { position: "CB", score: 82, label: "High" },
      { position: "WR", score: 74, label: "Moderate" },
    ],
    upcomingPicks: ["1.3", "2.35", "3.67", "4.104"],
  },

  ATL: {
    name: "Atlanta Falcons",
    abbreviation: "ATL",
    gm: "Ian Cunningham",
    headCoach: "Kevin Stefanski",
    offensiveScheme: "Wide Zone / Play Action",
    defensiveScheme: "Multiple Front",
    window: "Win Now / Unstable",
    needs: [
      { position: "EDGE", score: 95, label: "Critical" },
      { position: "CB", score: 83, label: "High" },
      { position: "WR", score: 76, label: "Moderate" },
      { position: "LB", score: 67, label: "Low" },
    ],
    upcomingPicks: ["1.15", "2.47", "3.79", "4.116"],
  },

  BAL: {
    name: "Baltimore Ravens",
    abbreviation: "BAL",
    gm: "Eric DeCosta",
    headCoach: "Jesse Minter",
    offensiveScheme: "Power Spread / QB Run Game",
    defensiveScheme: "Multiple Pressure",
    window: "Super Bowl Contender",
    needs: [
      { position: "EDGE", score: 86, label: "High" },
      { position: "CB", score: 82, label: "High" },
      { position: "OT", score: 78, label: "Moderate" },
      { position: "WR", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.24", "2.56", "3.88", "4.125"],
  },

  BUF: {
    name: "Buffalo Bills",
    abbreviation: "BUF",
    gm: "Brandon Beane",
    headCoach: "Joe Brady",
    offensiveScheme: "Spread / Vertical Passing",
    defensiveScheme: "Zone Match",
    window: "Super Bowl Contender",
    needs: [
      { position: "WR", score: 88, label: "High" },
      { position: "CB", score: 84, label: "High" },
      { position: "DL", score: 78, label: "Moderate" },
      { position: "S", score: 72, label: "Moderate" },
    ],
    upcomingPicks: ["1.25", "2.57", "3.89", "4.126"],
  },

  CAR: {
    name: "Carolina Panthers",
    abbreviation: "CAR",
    gm: "Dan Morgan",
    headCoach: "Dave Canales",
    offensiveScheme: "QB Friendly / Play Action",
    defensiveScheme: "3-4 Multiple",
    window: "Rebuild / Ascending",
    needs: [
      { position: "EDGE", score: 94, label: "Critical" },
      { position: "WR", score: 88, label: "High" },
      { position: "CB", score: 82, label: "High" },
      { position: "DL", score: 75, label: "Moderate" },
    ],
    upcomingPicks: ["1.10", "2.42", "3.74", "4.111"],
  },

  CHI: {
    name: "Chicago Bears",
    abbreviation: "CHI",
    gm: "Ryan Poles",
    headCoach: "Ben Johnson",
    offensiveScheme: "Modern Spread / Play Action",
    defensiveScheme: "4-3 Zone",
    window: "Ascending",
    needs: [
      { position: "DL", score: 86, label: "High" },
      { position: "EDGE", score: 82, label: "High" },
      { position: "IOL", score: 76, label: "Moderate" },
      { position: "S", score: 68, label: "Low" },
    ],
    upcomingPicks: ["1.16", "2.48", "3.80", "4.117"],
  },

  CIN: {
    name: "Cincinnati Bengals",
    abbreviation: "CIN",
    gm: "Duke Tobin",
    headCoach: "Zac Taylor",
    offensiveScheme: "Shotgun Spread",
    defensiveScheme: "Multiple Front",
    window: "Win Now",
    needs: [
      { position: "DL", score: 91, label: "Critical" },
      { position: "EDGE", score: 86, label: "High" },
      { position: "CB", score: 80, label: "High" },
      { position: "TE", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.18", "2.50", "3.82", "4.119"],
  },

  CLE: {
    name: "Cleveland Browns",
    abbreviation: "CLE",
    gm: "Andrew Berry",
    headCoach: "Todd Monken",
    offensiveScheme: "Wide Zone / Play Action",
    defensiveScheme: "Aggressive 4-3",
    window: "Win Now / Retool",
    needs: [
      { position: "QB", score: 94, label: "Critical" },
      { position: "OT", score: 85, label: "High" },
      { position: "WR", score: 78, label: "Moderate" },
      { position: "DL", score: 72, label: "Moderate" },
    ],
    upcomingPicks: ["1.4", "2.36", "3.68", "4.105"],
  },

  DAL: {
    name: "Dallas Cowboys",
    abbreviation: "DAL",
    gm: "Jerry Jones",
    headCoach: "Brian Schottenheimer",
    offensiveScheme: "Pro Style / Vertical Concepts",
    defensiveScheme: "Multiple Pressure",
    window: "Win Now",
    needs: [
      { position: "RB", score: 86, label: "High" },
      { position: "WR", score: 82, label: "High" },
      { position: "DL", score: 77, label: "Moderate" },
      { position: "CB", score: 72, label: "Moderate" },
    ],
    upcomingPicks: ["1.12", "2.44", "3.76", "4.113"],
  },

  DEN: {
    name: "Denver Broncos",
    abbreviation: "DEN",
    gm: "George Paton",
    headCoach: "Sean Payton",
    offensiveScheme: "West Coast / Timing",
    defensiveScheme: "Multiple Front",
    window: "Ascending",
    needs: [
      { position: "TE", score: 86, label: "High" },
      { position: "WR", score: 82, label: "High" },
      { position: "LB", score: 74, label: "Moderate" },
      { position: "DL", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.21", "2.53", "3.85", "4.122"],
  },

  DET: {
    name: "Detroit Lions",
    abbreviation: "DET",
    gm: "Brad Holmes",
    headCoach: "Dan Campbell",
    offensiveScheme: "Power / Play Action",
    defensiveScheme: "Aggressive Man Coverage",
    window: "Super Bowl Contender",
    needs: [
      { position: "EDGE", score: 84, label: "High" },
      { position: "CB", score: 78, label: "Moderate" },
      { position: "IOL", score: 72, label: "Moderate" },
      { position: "WR", score: 66, label: "Low" },
    ],
    upcomingPicks: ["1.29", "2.61", "3.93", "4.130"],
  },

  GB: {
    name: "Green Bay Packers",
    abbreviation: "GB",
    gm: "Brian Gutekunst",
    headCoach: "Matt LaFleur",
    offensiveScheme: "Wide Zone / Play Action",
    defensiveScheme: "4-3 Multiple",
    window: "Ascending / Contender",
    needs: [
      { position: "CB", score: 86, label: "High" },
      { position: "EDGE", score: 80, label: "High" },
      { position: "WR", score: 72, label: "Moderate" },
      { position: "IOL", score: 68, label: "Low" },
    ],
    upcomingPicks: ["1.23", "2.55", "3.87", "4.124"],
  },

  HOU: {
    name: "Houston Texans",
    abbreviation: "HOU",
    gm: "Nick Caserio",
    headCoach: "DeMeco Ryans",
    offensiveScheme: "Shanahan / Play Action",
    defensiveScheme: "4-3 Attack",
    window: "Ascending / Contender",
    needs: [
      { position: "IOL", score: 86, label: "High" },
      { position: "DL", score: 80, label: "High" },
      { position: "WR", score: 74, label: "Moderate" },
      { position: "S", score: 68, label: "Low" },
    ],
    upcomingPicks: ["1.22", "2.54", "3.86", "4.123"],
  },

  IND: {
    name: "Indianapolis Colts",
    abbreviation: "IND",
    gm: "Chris Ballard",
    headCoach: "Shane Steichen",
    offensiveScheme: "Spread / QB Run Game",
    defensiveScheme: "4-3 Zone",
    window: "Retool",
    needs: [
      { position: "QB", score: 90, label: "Critical" },
      { position: "TE", score: 84, label: "High" },
      { position: "CB", score: 78, label: "Moderate" },
      { position: "S", score: 72, label: "Moderate" },
    ],
    upcomingPicks: ["1.1", "1.14", "2.33", "3.65"],
  },

  JAX: {
    name: "Jacksonville Jaguars",
    abbreviation: "JAX",
    gm: "James Gladstone",
    headCoach: "Liam Coen",
    offensiveScheme: "Modern Pass Game",
    defensiveScheme: "Multiple Front",
    window: "Retool / Ascending",
    needs: [
      { position: "CB", score: 88, label: "High" },
      { position: "DL", score: 84, label: "High" },
      { position: "IOL", score: 78, label: "Moderate" },
      { position: "WR", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.2", "2.34", "3.66", "4.103"],
  },

  KC: {
    name: "Kansas City Chiefs",
    abbreviation: "KC",
    gm: "Brett Veach",
    headCoach: "Andy Reid",
    offensiveScheme: "Spread / Motion Passing",
    defensiveScheme: "Multiple Pressure",
    window: "Super Bowl Contender",
    needs: [
      { position: "OT", score: 84, label: "High" },
      { position: "WR", score: 78, label: "Moderate" },
      { position: "DL", score: 72, label: "Moderate" },
      { position: "CB", score: 66, label: "Low" },
    ],
    upcomingPicks: ["1.31", "2.63", "3.95", "4.132"],
  },

  LV: {
    name: "Las Vegas Raiders",
    abbreviation: "LV",
    gm: "John Spytek",
    headCoach: "Klint Kubiak",
    offensiveScheme: "Power / Vertical Passing",
    defensiveScheme: "4-3 Attack",
    window: "Retool",
    needs: [
      { position: "QB", score: 92, label: "Critical" },
      { position: "CB", score: 84, label: "High" },
      { position: "WR", score: 78, label: "Moderate" },
      { position: "IOL", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.9", "2.41", "3.73", "4.110"],
  },

  LAC: {
    name: "Los Angeles Chargers",
    abbreviation: "LAC",
    gm: "Joe Hortiz",
    headCoach: "Jim Harbaugh",
    offensiveScheme: "Power / Play Action",
    defensiveScheme: "Multiple Pressure",
    window: "Ascending",
    needs: [
      { position: "WR", score: 86, label: "High" },
      { position: "TE", score: 80, label: "High" },
      { position: "DL", score: 76, label: "Moderate" },
      { position: "CB", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.20", "2.52", "3.84", "4.121"],
  },

  LAR: {
    name: "Los Angeles Rams",
    abbreviation: "LAR",
    gm: "Les Snead",
    headCoach: "Sean McVay",
    offensiveScheme: "Wide Zone / Play Action",
    defensiveScheme: "Multiple Front",
    window: "Win Now / Retool",
    needs: [
      { position: "OT", score: 82, label: "High" },
      { position: "CB", score: 78, label: "Moderate" },
      { position: "LB", score: 72, label: "Moderate" },
      { position: "QB", score: 68, label: "Low" },
    ],
    upcomingPicks: ["1.26", "2.58", "3.90", "4.127"],
  },

  MIA: {
    name: "Miami Dolphins",
    abbreviation: "MIA",
    gm: "Jon-Eric Sullivan",
    headCoach: "Jeff Hafley",
    offensiveScheme: "Motion / Wide Zone Speed",
    defensiveScheme: "Multiple Front",
    window: "Win Now",
    needs: [
      { position: "IOL", score: 88, label: "High" },
      { position: "DL", score: 82, label: "High" },
      { position: "S", score: 76, label: "Moderate" },
      { position: "OT", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.13", "2.45", "3.77", "4.114"],
  },

  MIN: {
    name: "Minnesota Vikings",
    abbreviation: "MIN",
    gm: "Nolan Teasley",
    headCoach: "Kevin O'Connell",
    offensiveScheme: "McVay Tree / Play Action",
    defensiveScheme: "Aggressive Multiple",
    window: "Ascending",
    needs: [
      { position: "CB", score: 86, label: "High" },
      { position: "DL", score: 80, label: "High" },
      { position: "IOL", score: 74, label: "Moderate" },
      { position: "RB", score: 66, label: "Low" },
    ],
    upcomingPicks: ["1.27", "2.59", "3.91", "4.128"],
  },

  NE: {
    name: "New England Patriots",
    abbreviation: "NE",
    gm: "Eliot Wolf",
    headCoach: "Mike Vrabel",
    offensiveScheme: "Power / Play Action",
    defensiveScheme: "Multiple Front",
    window: "Rebuild / Ascending",
    needs: [
      { position: "WR", score: 90, label: "Critical" },
      { position: "OT", score: 86, label: "High" },
      { position: "EDGE", score: 78, label: "Moderate" },
      { position: "CB", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.7", "2.39", "3.71", "4.108"],
  },

  NO: {
    name: "New Orleans Saints",
    abbreviation: "NO",
    gm: "Mickey Loomis",
    headCoach: "Kellen Moore",
    offensiveScheme: "Modern West Coast",
    defensiveScheme: "4-3 Multiple",
    window: "Retool",
    needs: [
      { position: "QB", score: 88, label: "High" },
      { position: "OT", score: 84, label: "High" },
      { position: "DL", score: 78, label: "Moderate" },
      { position: "WR", score: 72, label: "Moderate" },
    ],
    upcomingPicks: ["1.8", "2.40", "3.72", "4.109"],
  },

  NYG: {
    name: "New York Giants",
    abbreviation: "NYG",
    gm: "Joe Schoen",
    headCoach: "John Harbaugh",
    offensiveScheme: "Spread / Vertical Concepts",
    defensiveScheme: "Multiple Pressure",
    window: "Rebuild / Retool",
    needs: [
      { position: "QB", score: 95, label: "Critical" },
      { position: "CB", score: 84, label: "High" },
      { position: "IOL", score: 76, label: "Moderate" },
      { position: "WR", score: 72, label: "Moderate" },
    ],
    upcomingPicks: ["1.5", "2.37", "3.69", "4.106"],
  },

  NYJ: {
    name: "New York Jets",
    abbreviation: "NYJ",
    gm: "Darren Mougey",
    headCoach: "Aaron Glenn",
    offensiveScheme: "Balanced / Play Action",
    defensiveScheme: "Aggressive 4-3",
    window: "Retool",
    needs: [
      { position: "QB", score: 90, label: "Critical" },
      { position: "TE", score: 82, label: "High" },
      { position: "S", score: 76, label: "Moderate" },
      { position: "IOL", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.11", "2.43", "3.75", "4.112"],
  },

  PHI: {
    name: "Philadelphia Eagles",
    abbreviation: "PHI",
    gm: "Howie Roseman",
    headCoach: "Nick Sirianni",
    offensiveScheme: "Spread / RPO",
    defensiveScheme: "Multiple Front",
    window: "Super Bowl Contender",
    needs: [
      { position: "EDGE", score: 82, label: "High" },
      { position: "CB", score: 78, label: "Moderate" },
      { position: "IOL", score: 72, label: "Moderate" },
      { position: "LB", score: 66, label: "Low" },
    ],
    upcomingPicks: ["1.30", "2.62", "3.94", "4.131"],
  },

  PIT: {
    name: "Pittsburgh Steelers",
    abbreviation: "PIT",
    gm: "Omar Khan",
    headCoach: "Mike McCarthy",
    offensiveScheme: "Power / Play Action",
    defensiveScheme: "3-4 Zone Pressure",
    window: "Win Now / Retool",
    needs: [
      { position: "QB", score: 90, label: "Critical" },
      { position: "WR", score: 84, label: "High" },
      { position: "DL", score: 78, label: "Moderate" },
      { position: "CB", score: 72, label: "Moderate" },
    ],
    upcomingPicks: ["1.19", "2.51", "3.83", "4.120"],
  },

  SF: {
    name: "San Francisco 49ers",
    abbreviation: "SF",
    gm: "John Lynch",
    headCoach: "Kyle Shanahan",
    offensiveScheme: "Wide Zone / Motion",
    defensiveScheme: "4-3 Attack",
    window: "Super Bowl Contender",
    needs: [
      { position: "OT", score: 86, label: "High" },
      { position: "DL", score: 82, label: "High" },
      { position: "CB", score: 76, label: "Moderate" },
      { position: "IOL", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.28", "2.60", "3.92", "4.129"],
  },

  SEA: {
    name: "Seattle Seahawks",
    abbreviation: "SEA",
    gm: "John Schneider",
    headCoach: "Mike Macdonald",
    offensiveScheme: "Balanced / Play Action",
    defensiveScheme: "Macdonald Multiple",
    window: "Ascending",
    needs: [
      { position: "IOL", score: 86, label: "High" },
      { position: "LB", score: 80, label: "High" },
      { position: "EDGE", score: 74, label: "Moderate" },
      { position: "TE", score: 68, label: "Low" },
    ],
    upcomingPicks: ["1.17", "2.49", "3.81", "4.118"],
  },

  TB: {
    name: "Tampa Bay Buccaneers",
    abbreviation: "TB",
    gm: "Jason Licht",
    headCoach: "Todd Bowles",
    offensiveScheme: "Spread / Vertical Passing",
    defensiveScheme: "3-4 Pressure",
    window: "Win Now",
    needs: [
      { position: "EDGE", score: 86, label: "High" },
      { position: "LB", score: 80, label: "High" },
      { position: "CB", score: 74, label: "Moderate" },
      { position: "IOL", score: 68, label: "Low" },
    ],
    upcomingPicks: ["1.32", "2.64", "3.96", "4.133"],
  },

  TEN: {
    name: "Tennessee Titans",
    abbreviation: "TEN",
    gm: "Mike Borgonzi",
    headCoach: "Robert Saleh",
    offensiveScheme: "Pass First / Spread Concepts",
    defensiveScheme: "Multiple Front",
    window: "Rebuild / Retool",
    needs: [
      { position: "OT", score: 88, label: "High" },
      { position: "EDGE", score: 84, label: "High" },
      { position: "WR", score: 78, label: "Moderate" },
      { position: "S", score: 70, label: "Moderate" },
    ],
    upcomingPicks: ["1.6", "2.38", "3.70", "4.107"],
  },

  WAS: {
    name: "Washington Commanders",
    abbreviation: "WAS",
    gm: "Adam Peters",
    headCoach: "Dan Quinn",
    offensiveScheme: "Spread / QB Movement",
    defensiveScheme: "4-3 Multiple",
    window: "Ascending",
    needs: [
      { position: "EDGE", score: 86, label: "High" },
      { position: "OT", score: 80, label: "High" },
      { position: "CB", score: 74, label: "Moderate" },
      { position: "WR", score: 68, label: "Low" },
    ],
    upcomingPicks: ["1.7", "2.39", "3.71", "4.108"],
  },
};

export const activeTeam = teamProfiles.ARI;

export function getTeamProfile(abbreviation) {
  return teamProfiles[abbreviation] || activeTeam;
}