import assert from "node:assert/strict";
import {NFL_HISTORICAL_AVAILABILITY_REQUIRED_COLUMNS as REQUIRED,qualifyNFLHistoricalAvailabilitySeason} from "../teamIntelligence/strength/calibration/index.js";
const tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
const good=qualifyNFLHistoricalAvailabilitySeason({season:2024,sourceAvailable:true,sourceFormat:"CSV",sourceUrl:"x",rowCount:100,columns:[...REQUIRED],gsisCoverageRate:.99,dateModifiedCoverageRate:1,pregameSafeRate:.98,duplicateRate:.01});
t("contract",()=>assert.equal(good.contractVersion,"FIE-NFL-HISTORICAL-AVAILABILITY-QUALIFICATION-1.0.0"));
t("season",()=>assert.equal(good.season,2024));
t("schema_good",()=>assert.equal(good.schemaQualified,true));
t("identity_good",()=>assert.equal(good.identityQualified,true));
t("temporal_good",()=>assert.equal(good.temporalQualified,true));
t("join_good",()=>assert.equal(good.qualifiedForJoin,true));
t("calibration_still_false",()=>assert.equal(good.calibrationAuthorized,false));
t("weights_still_false",()=>assert.equal(good.learnedWeightsAuthorized,false));
const missing=qualifyNFLHistoricalAvailabilitySeason({season:2023,sourceAvailable:true,rowCount:10,columns:["season","team"],gsisCoverageRate:1,pregameSafeRate:1});
t("missing_columns_detected",()=>assert.ok(missing.missingColumns.includes("gsis_id")));
t("missing_schema_fails",()=>assert.equal(missing.schemaQualified,false));
t("missing_join_fails",()=>assert.equal(missing.qualifiedForJoin,false));
const lowId=qualifyNFLHistoricalAvailabilitySeason({season:2022,sourceAvailable:true,rowCount:10,columns:[...REQUIRED],gsisCoverageRate:.7,pregameSafeRate:1});
t("low_id_fails_identity",()=>assert.equal(lowId.identityQualified,false));
t("low_id_fails_join",()=>assert.equal(lowId.qualifiedForJoin,false));
const late=qualifyNFLHistoricalAvailabilitySeason({season:2022,sourceAvailable:true,rowCount:10,columns:[...REQUIRED],gsisCoverageRate:1,pregameSafeRate:.7});
t("late_fails_temporal",()=>assert.equal(late.temporalQualified,false));
t("late_fails_join",()=>assert.equal(late.qualifiedForJoin,false));
const absent=qualifyNFLHistoricalAvailabilitySeason({season:2025,sourceAvailable:false,rowCount:0,columns:[]});
t("absent_source_false",()=>assert.equal(absent.sourceAvailable,false));
t("absent_schema_false",()=>assert.equal(absent.schemaQualified,false));
t("absent_identity_false",()=>assert.equal(absent.identityQualified,false));
t("absent_temporal_false",()=>assert.equal(absent.temporalQualified,false));
t("absent_join_false",()=>assert.equal(absent.qualifiedForJoin,false));
t("required_has_report_status",()=>assert.ok(REQUIRED.includes("report_status")));
t("required_has_practice_status",()=>assert.ok(REQUIRED.includes("practice_status")));
t("required_has_date_modified",()=>assert.ok(REQUIRED.includes("date_modified")));
t("required_has_gsis",()=>assert.ok(REQUIRED.includes("gsis_id")));
t("required_has_week",()=>assert.ok(REQUIRED.includes("week")));
const exact=qualifyNFLHistoricalAvailabilitySeason({season:2024,sourceAvailable:true,rowCount:1,columns:[...REQUIRED],gsisCoverageRate:.95,pregameSafeRate:.95});
t("threshold_identity_inclusive",()=>assert.equal(exact.identityQualified,true));
t("threshold_temporal_inclusive",()=>assert.equal(exact.temporalQualified,true));
t("threshold_join_inclusive",()=>assert.equal(exact.qualifiedForJoin,true));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Historical Availability Source Qualification",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D1B-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
