import assert from "node:assert/strict";
import {getNFLHistoricalDepthChartEvidenceGovernance as get} from "../teamIntelligence/strength/calibration/index.js";
const g=get(),tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
t("contract",()=>assert.equal(g.contractVersion,"FIE-NFL-HISTORICAL-DEPTH-CHART-EVIDENCE-GOVERNANCE-1.0.0"));
t("provider",()=>assert.equal(g.provider,"nflverse/nflverse-data"));
t("release",()=>assert.equal(g.releaseTag,"depth_charts"));
t("url_pattern",()=>assert.ok(g.csvUrlTemplate.endsWith("/depth_charts/depth_charts_{season}.csv")));
t("minimum_2001",()=>assert.equal(g.documentedMinimumSeason,2001));
t("2022",()=>assert.ok(g.targetSeasons.includes(2022)));
t("2023",()=>assert.ok(g.targetSeasons.includes(2023)));
t("2024",()=>assert.ok(g.targetSeasons.includes(2024)));
t("gsis_canonical",()=>assert.equal(g.canonicalIdentityField,"gsis_id"));
t("week_scoped",()=>assert.equal(g.weekScopedHistoricalStructure,true));
t("timestamped_2025",()=>assert.equal(g.timestampedStructureFrom2025,true));
t("depth_order_required",()=>assert.equal(g.depthOrderingRequired,true));
t("week_scope_not_auto_safe",()=>assert.equal(g.weekScopeAloneAuthorizesPregameReplacement,false));
t("snap_only_corroborates",()=>assert.equal(g.postgameSnapCountsMayCorroborateButNotDefineReplacement,true));
t("no_roster_guess",()=>assert.equal(g.rosterOrderGuessAllowed,false));
t("no_name_guess",()=>assert.equal(g.nameGuessAllowed,false));
t("no_mapping_generated",()=>assert.equal(g.replacementMappingsGeneratedByThisSprint,false));
t("calibration_blocked",()=>assert.equal(g.calibrationAuthorized,false));
t("weights_blocked",()=>assert.equal(g.learnedWeightsAuthorized,false));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Historical Depth Chart Evidence Governance",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D1C2B2-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
