import assert from "node:assert/strict";
import {getNFLHistoricalOfficialPregameEvidenceExpansionGovernance as get} from "../teamIntelligence/strength/calibration/index.js";
const g=get(),tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
t("contract",()=>assert.equal(g.contractVersion,"FIE-NFL-HISTORICAL-OFFICIAL-PREGAME-EVIDENCE-EXPANSION-GOVERNANCE-1.0.0"));
t("schedule_driven",()=>assert.equal(g.discoveryMode,"SCHEDULE_DRIVEN_GAP_TARGETING"));
t("official_required",()=>assert.equal(g.officialDomainRequired,true));
t("known_game_required",()=>assert.equal(g.knownGameTargetRequired,true));
t("opponent_or_week_required",()=>assert.equal(g.opponentOrExplicitWeekTargetRequired,true));
t("timestamp_required",()=>assert.equal(g.publicationTimestampRequired,true));
t("must_precede",()=>assert.equal(g.publicationMustPrecedeKickoff,true));
t("preserve_existing",()=>assert.equal(g.existingQualifiedEvidencePreserved,true));
t("gap_only",()=>assert.equal(g.fetchOnlyGapTeamWeeks,true));
t("prefilter",()=>assert.equal(g.articleKeywordPrefilterRequired,true));
t("pdf_discovery",()=>assert.equal(g.officialPdfLinksMayBeDiscoveredFromOfficialArticles,true));
t("pdf_temporal",()=>assert.equal(g.pdfPublicationMustStillBeTemporallyAnchored,true));
t("no_mapping",()=>assert.equal(g.replacementMappingsGeneratedByThisSprint,false));
t("no_inferred_time",()=>assert.equal(g.inferredTimestampAllowed,false));
t("no_nonofficial",()=>assert.equal(g.nonOfficialSourceAllowed,false));
t("no_calibration",()=>assert.equal(g.calibrationAuthorized,false));
t("no_weights",()=>assert.equal(g.learnedWeightsAuthorized,false));
t("threshold_obs",()=>assert.equal(g.qualificationThresholds.minimumPregameSafeObservations,100));
t("threshold_teams",()=>assert.equal(g.qualificationThresholds.minimumTeamBreadth,16));
t("threshold_seasons",()=>assert.equal(g.qualificationThresholds.minimumSeasonBreadth,3));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Historical Official Pregame Evidence Expansion Governance",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D1C2B2B-R3-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
