import assert from "node:assert/strict";
import {getNFLHistoricalSnapEvidenceAcquisitionGovernance as get} from "../teamIntelligence/strength/calibration/index.js";
const g=get(); const tests=[]; const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
t("contract",()=>assert.equal(g.contractVersion,"FIE-NFL-HISTORICAL-SNAP-EVIDENCE-ACQUISITION-GOVERNANCE-1.0.0"));
t("provider",()=>assert.equal(g.canonicalProvider,"nflverse/nflverse-data"));
t("release",()=>assert.equal(g.releaseTag,"snap_counts"));
t("url_pattern",()=>assert.ok(g.csvUrlTemplate.endsWith("/snap_counts/snap_counts_{season}.csv")));
t("min_2012",()=>assert.equal(g.minimumSupportedSeason,2012));
t("2022_target",()=>assert.ok(g.intendedSeasons.includes(2022)));
t("2023_target",()=>assert.ok(g.intendedSeasons.includes(2023)));
t("2024_target",()=>assert.ok(g.intendedSeasons.includes(2024)));
t("source_id_pfr",()=>assert.equal(g.sourceIdentityField,"pfr_player_id"));
t("canonical_id_gsis",()=>assert.equal(g.canonicalIdentityField,"gsis_id"));
t("identity_not_equated",()=>assert.equal(g.sourceIdentityMayMasqueradeAsCanonicalIdentity,false));
t("postgame_only",()=>assert.equal(g.postgameParticipationEvidenceOnly,true));
t("pregame_replacement_blocked",()=>assert.equal(g.pregameReplacementDeterminationAuthorized,false));
t("no_current_backfill",()=>assert.equal(g.currentRatingBackfillAllowed,false));
t("no_weights",()=>assert.equal(g.learnedWeightsAuthorized,false));
t("no_dataset_mutation",()=>assert.equal(g.datasetMutationAuthorized,false));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Historical Snap Evidence Acquisition Governance",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D1C2B1-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
