import assert from "node:assert/strict";
import {getNFLHistoricalOfficialTeamPublicationGovernance as get} from "../teamIntelligence/strength/calibration/index.js";
const g=get(),tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
t("contract",()=>assert.equal(g.contractVersion,"FIE-NFL-HISTORICAL-OFFICIAL-TEAM-PUBLICATION-GOVERNANCE-1.0.0"));
t("official_required",()=>assert.equal(g.officialTeamDomainRequired,true));
t("timestamp_required",()=>assert.equal(g.publicationTimestampRequired,true));
t("team_week_required",()=>assert.equal(g.teamWeekMappingRequired,true));
t("kickoff_compare",()=>assert.equal(g.kickoffComparisonRequired,true));
t("must_precede",()=>assert.equal(g.publicationMustPrecedeKickoff,true));
t("depth_allowed",()=>assert.ok(g.allowedPublicationTypes.includes("DEPTH_CHART_RELEASE")));
t("starter_allowed",()=>assert.ok(g.allowedPublicationTypes.includes("EXPLICIT_STARTER_ANNOUNCEMENT")));
t("game_release_allowed",()=>assert.ok(g.allowedPublicationTypes.includes("WEEKLY_GAME_RELEASE")));
t("title_not_replacement",()=>assert.equal(g.articleTitleMatchAloneInsufficientForReplacement,true));
t("publication_can_anchor_depth",()=>assert.equal(g.sourcePublicationMayAnchorWeekScopedDepthChart,true));
t("starter_can_identify",()=>assert.equal(g.explicitStarterAnnouncementMayIdentifyStarter,true));
t("no_mapping_yet",()=>assert.equal(g.replacementMappingsGeneratedByThisSprint,false));
t("no_inferred_timestamp",()=>assert.equal(g.inferredPublicationTimestampAllowed,false));
t("no_nonofficial",()=>assert.equal(g.nonOfficialDomainsAllowed,false));
t("no_weights",()=>assert.equal(g.learnedWeightsAuthorized,false));
t("no_calibration",()=>assert.equal(g.calibrationAuthorized,false));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Historical Official Team Publication Governance",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D1C2B2B-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
