import assert from "node:assert/strict";
import {getNFLHistoricalRealDatasetV1Manifest} from "../teamIntelligence/strength/calibration/index.js";
const m=getNFLHistoricalRealDatasetV1Manifest();
const tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
t("contract",()=>assert.equal(m.contractVersion,"FIE-NFL-HISTORICAL-REAL-DATASET-V1-1.0.0"));
t("dataset_id",()=>assert.equal(m.datasetId,"LBHT-NFL-HISTORICAL-CALIBRATION-V1"));
t("data_not_bundled",()=>assert.equal(m.status,"ACQUISITION_RUNNER_READY_DATA_NOT_BUNDLED"));
t("default_2022",()=>assert.ok(m.defaultSeasonRange.includes(2022)));
t("default_2025",()=>assert.ok(m.defaultSeasonRange.includes(2025)));
t("schedule_source",()=>assert.equal(m.sources.schedules.id,"NFLVERSE_SCHEDULES"));
t("schedule_csv",()=>assert.equal(m.sources.schedules.format,"CSV"));
t("pbp_source",()=>assert.equal(m.sources.playByPlay.id,"NFLVERSE_PBP"));
t("pbp_tag_url",()=>assert.ok(m.sources.playByPlay.urlTemplate.includes("/download/pbp/play_by_play_{season}.csv.gz")));
t("pbp_min_1999",()=>assert.equal(m.sources.playByPlay.minimumSeason,1999));
t("roster_source",()=>assert.equal(m.sources.weeklyRosters.id,"NFLVERSE_WEEKLY_ROSTERS"));
t("roster_url",()=>assert.ok(m.sources.weeklyRosters.urlTemplate.includes("/download/weekly_rosters/roster_weekly_{season}.csv")));
t("roster_min_2002",()=>assert.equal(m.sources.weeklyRosters.minimumSeason,2002));
t("no_db_write",()=>assert.equal(m.outputPolicy.persistentDatabaseWrite,false));
t("local_staging",()=>assert.equal(m.outputPolicy.localStagingOnly,true));
t("raw_cache",()=>assert.equal(m.outputPolicy.rawSourceCaching,true));
t("no_weights",()=>assert.equal(m.outputPolicy.learnedWeights,false));
t("no_scores",()=>assert.equal(m.outputPolicy.teamStrengthScores,false));
t("current_game_pbp_blocked",()=>assert.equal(m.evidencePolicy.currentGamePbpAsPregameFeatureAllowed,false));
t("future_pbp_blocked",()=>assert.equal(m.evidencePolicy.futureWeekPbpAllowed,false));
t("prior_games_only",()=>assert.equal(m.evidencePolicy.performanceUsesPriorGamesOnly,true));
t("recent_prior_only",()=>assert.equal(m.evidencePolicy.recentFormUsesPriorGamesOnly,true));
t("roster_team_week",()=>assert.equal(m.evidencePolicy.rosterUsesRequestedTeamWeekOnly,true));
t("missing_injury_null",()=>assert.equal(m.evidencePolicy.missingInjuriesRemainNull,true));
t("missing_caliber_null",()=>assert.equal(m.evidencePolicy.missingPlayerCaliberRemainsNull,true));
t("missing_coaching_null",()=>assert.equal(m.evidencePolicy.missingCoachingRemainsNull,true));
t("missing_scheme_null",()=>assert.equal(m.evidencePolicy.missingSchemeRemainsNull,true));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Real Historical Acquisition & Calibration Dataset V1 Foundation",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
