import assert from "node:assert/strict";
import {auditNFLHistoricalDatasetQuality,assessNFLHistoricalExperimentEligibility} from "../teamIntelligence/strength/calibration/index.js";
const mk=(domain,season=2025,week=1,gameId="g1",team="BAL",safe=true,prov=true)=>({domain,season,week,gameId,team,safeForPregameCalibration:safe,sourceId:prov?"S":null,provenance:prov?{provider:"P"}:{}});
const records=[mk("SCHEDULES_RESULTS"),mk("TEAM_STATS"),mk("WEEKLY_ROSTERS"),mk("INJURIES"),mk("PLAYER_CALIBER"),mk("COACHING"),mk("SCHEME"),
mk("SCHEDULES_RESULTS",2024,2,"g2"),mk("TEAM_STATS",2024,2,"g2"),mk("INJURIES",2024,2,"g2","BAL",false),mk("TEAM_STATS",2023,3,"g3","CAR",true,false)];
const a=auditNFLHistoricalDatasetQuality(records),e=assessNFLHistoricalExperimentEligibility(a,1);
const tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(x){tests.push([n,false,x.message])}};
t("audit_contract",()=>assert.equal(a.contractVersion,"FIE-NFL-HISTORICAL-DATASET-QUALITY-AUDIT-1.0.0"));
t("not_calibrated",()=>assert.equal(a.status,"AUDITED_NOT_CALIBRATED"));
t("universe_three",()=>assert.equal(a.universeObservationKeyCount,3));
t("schedule_count",()=>assert.equal(a.domains.SCHEDULES_RESULTS.recordCount,2));
t("schedule_safe",()=>assert.equal(a.domains.SCHEDULES_RESULTS.safePregameKeyCount,2));
t("injury_unsafe_count",()=>assert.equal(a.domains.INJURIES.unsafeRecordCount,1));
t("injury_safety_half",()=>assert.equal(a.domains.INJURIES.temporalSafetyRate,.5));
t("team_stats_provenance",()=>assert.equal(a.domains.TEAM_STATS.provenanceCoverageRate,2/3));
t("team_stats_min_season",()=>assert.equal(a.domains.TEAM_STATS.minimumSeason,2023));
t("team_stats_max_season",()=>assert.equal(a.domains.TEAM_STATS.maximumSeason,2025));
t("missing_domain_zero",()=>assert.equal(a.domains.DEPTH_CHARTS.recordCount,0));
t("missing_domain_null_rate",()=>assert.equal(a.domains.DEPTH_CHARTS.temporalSafetyRate,null));
t("performance_overlap_two",()=>assert.equal(a.overlaps.performance.safeObservationKeyCount,2));
t("availability_overlap_one",()=>assert.equal(a.overlaps.availability.safeObservationKeyCount,1));
t("availability_caliber_one",()=>assert.equal(a.overlaps.availabilityCaliber.safeObservationKeyCount,1));
t("coaching_scheme_one",()=>assert.equal(a.overlaps.coachingScheme.safeObservationKeyCount,1));
t("weights_null",()=>assert.equal(a.learnedWeights,null));
t("coefficients_null",()=>assert.equal(a.learnedCoefficients,null));
t("scores_null",()=>assert.equal(a.teamStrengthScores,null));
t("eligibility_contract",()=>assert.equal(e.contractVersion,"FIE-NFL-HISTORICAL-EXPERIMENT-ELIGIBILITY-1.0.0"));
t("performance_eligible",()=>assert.equal(e.experiments.PERFORMANCE.eligible,true));
t("availability_eligible",()=>assert.equal(e.experiments.AVAILABILITY.eligible,true));
t("availability_caliber_eligible",()=>assert.equal(e.experiments.AVAILABILITY_CALIBER.eligible,true));
t("coaching_scheme_eligible",()=>assert.equal(e.experiments.COACHING_SCHEME.eligible,true));
t("replacement_not_eligible",()=>assert.equal(e.experiments.REPLACEMENT_CALIBER.eligible,false));
t("replacement_missing",()=>assert.ok(e.experiments.REPLACEMENT_CALIBER.missingDomains.includes("REPLACEMENT_CALIBER")));
t("calibration_execution_false",()=>assert.equal(e.authorizesCalibrationExecution,false));
t("coverage_not_equalized",()=>assert.notEqual(a.domains.TEAM_STATS.universeCoverageRate,a.domains.INJURIES.universeCoverageRate));
t("season_list_preserved",()=>assert.deepEqual([...a.domains.TEAM_STATS.seasons],[2023,2024,2025]));
t("minimum_threshold_preserved",()=>assert.equal(e.minimumSafeObservations,1));
const bad=tests.filter(x=>!x[1]);console.log(JSON.stringify({suite:"NFL Historical Coverage & Dataset Quality Audit",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9C-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));if(bad.length)process.exitCode=1;
