import assert from "node:assert/strict";
import {getNFLHistoricalPlayerIdentityResolutionGovernance as get} from "../teamIntelligence/strength/calibration/index.js";
const g=get(),tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
t("contract",()=>assert.equal(g.contractVersion,"FIE-NFL-HISTORICAL-PLAYER-IDENTITY-RESOLUTION-GOVERNANCE-1.0.0"));
t("provider",()=>assert.equal(g.provider,"nflverse/nflverse-data"));
t("release",()=>assert.equal(g.releaseTag,"players"));
t("url",()=>assert.ok(g.csvUrl.endsWith("/players/players.csv")));
t("source_pfr",()=>assert.equal(g.sourceIdentityField,"pfr_id"));
t("canonical_gsis",()=>assert.equal(g.canonicalIdentityField,"gsis_id"));
t("primary_gsis",()=>assert.equal(g.canonicalPrimaryKey,"gsis_id"));
t("exact_required",()=>assert.equal(g.exactIdMappingRequired,true));
t("no_name",()=>assert.equal(g.nameFallbackAllowed,false));
t("no_fuzzy",()=>assert.equal(g.fuzzyNameFallbackAllowed,false));
t("no_team_position_guess",()=>assert.equal(g.teamPositionGuessAllowed,false));
t("ambiguous_unresolved",()=>assert.equal(g.ambiguousMappingRemainsUnresolved,true));
t("missing_unresolved",()=>assert.equal(g.missingMappingRemainsUnresolved,true));
t("join_requires_identity",()=>assert.equal(g.canonicalJoinRequiresResolvedIdentity,true));
t("pregame_replacement_blocked",()=>assert.equal(g.pregameReplacementDeterminationAuthorized,false));
t("weights_blocked",()=>assert.equal(g.learnedWeightsAuthorized,false));
t("calibration_blocked",()=>assert.equal(g.calibrationAuthorized,false));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Historical Player Identity Resolution Governance",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D1C2B1A-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
