import assert from "node:assert/strict";
import {
 getNFLHistoricalAvailabilitySourceGovernance,resolveHistoricalPlayerIdentity,
 projectHistoricalPlayerCaliberEvidence,buildHistoricalAvailabilityCaliberObservation
} from "../teamIntelligence/strength/calibration/index.js";
const tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
const g=getNFLHistoricalAvailabilitySourceGovernance();
t("governance_version",()=>assert.equal(g.contractVersion,"FIE-NFL-HISTORICAL-AVAILABILITY-SOURCE-GOVERNANCE-1.0.0"));
t("injury_source_requires_qualification",()=>assert.equal(g.sources.nflverseInjuries.status,"QUALIFICATION_REQUIRED"));
t("2025_not_authorized",()=>assert.equal(g.sources.nflverseInjuries.mayAuthorize2025Acquisition,false));
t("roster_not_injury_proxy",()=>assert.equal(g.sources.weeklyRosters.mayInferInjuryFromRosterStatus,false));
t("pregame_required",()=>assert.equal(g.temporalPolicy.evidenceMustExistBeforeKickoff,true));
t("postkickoff_blocked",()=>assert.equal(g.temporalPolicy.postKickoffUpdatesAllowed,false));
t("unknown_null",()=>assert.equal(g.temporalPolicy.unknownRemainsNull,true));
t("weights_blocked",()=>assert.equal(g.calibrationPolicy.learnedAvailabilityWeightsAuthorized,false));
const id=resolveHistoricalPlayerIdentity({injuryRecord:{gsisId:"00-0031234"},rosterRecord:{gsisId:"00-0031234"}});
t("identity_resolved",()=>assert.equal(id.status,"RESOLVED"));
t("identity_canonical",()=>assert.equal(id.canonicalPlayerId,"00-0031234"));
const conflict=resolveHistoricalPlayerIdentity({injuryRecord:{gsisId:"A"},rosterRecord:{gsisId:"B"}});
t("identity_conflict",()=>assert.equal(conflict.status,"CONFLICT"));
t("identity_conflict_no_id",()=>assert.equal(conflict.canonicalPlayerId,null));
const missing=resolveHistoricalPlayerIdentity({});
t("identity_missing",()=>assert.equal(missing.status,"UNRESOLVED"));
const cal=projectHistoricalPlayerCaliberEvidence({identityResult:id,evaluationResult:{status:"AVAILABLE",caliber:91,confidence:.82,modelVersion:"M1"}});
t("caliber_available",()=>assert.equal(cal.status,"AVAILABLE"));
t("caliber_preserved",()=>assert.equal(cal.caliber,91));
t("caliber_confidence_preserved",()=>assert.equal(cal.confidence,.82));
t("caliber_model_version",()=>assert.equal(cal.modelVersion,"M1"));
const noCal=projectHistoricalPlayerCaliberEvidence({identityResult:id,evaluationResult:{status:"UNAVAILABLE"}});
t("missing_caliber_unavailable",()=>assert.equal(noCal.status,"UNAVAILABLE"));
t("missing_caliber_null",()=>assert.equal(noCal.caliber,null));
const badIdCal=projectHistoricalPlayerCaliberEvidence({identityResult:conflict,evaluationResult:{status:"AVAILABLE",caliber:99}});
t("conflicted_identity_blocks_caliber",()=>assert.equal(badIdCal.status,"UNAVAILABLE"));
const obs=buildHistoricalAvailabilityCaliberObservation({availability:{status:"OUT"},identity:id,caliber:cal,replacementCaliber:64});
t("observation_contract",()=>assert.equal(obs.contractVersion,"FIE-NFL-HISTORICAL-AVAILABILITY-CALIBER-OBSERVATION-1.0.0"));
t("out_is_unavailable",()=>assert.equal(obs.unavailable,true));
t("player_caliber_in_observation",()=>assert.equal(obs.playerCaliber,91));
t("replacement_preserved",()=>assert.equal(obs.replacementCaliber,64));
t("delta_computed",()=>assert.equal(obs.caliberDelta,27));
t("availability_experiment_eligible",()=>assert.equal(obs.eligibleForAvailabilityOnlyExperiment,true));
t("caliber_experiment_eligible",()=>assert.equal(obs.eligibleForAvailabilityCaliberExperiment,true));
t("replacement_experiment_eligible",()=>assert.equal(obs.eligibleForReplacementCaliberExperiment,true));
const noRep=buildHistoricalAvailabilityCaliberObservation({availability:{status:"QUESTIONABLE"},identity:id,caliber:cal});
t("missing_replacement_null",()=>assert.equal(noRep.replacementCaliber,null));
t("missing_replacement_not_eligible",()=>assert.equal(noRep.eligibleForReplacementCaliberExperiment,false));
const noGradeObs=buildHistoricalAvailabilityCaliberObservation({availability:{status:"OUT"},identity:id,caliber:noCal});
t("missing_grade_not_caliber_eligible",()=>assert.equal(noGradeObs.eligibleForAvailabilityCaliberExperiment,false));
t("missing_grade_still_availability_eligible",()=>assert.equal(noGradeObs.eligibleForAvailabilityOnlyExperiment,true));
const badIdObs=buildHistoricalAvailabilityCaliberObservation({availability:{status:"OUT"},identity:conflict,caliber:badIdCal});
t("conflict_player_id_null",()=>assert.equal(badIdObs.playerId,null));
const q=buildHistoricalAvailabilityCaliberObservation({availability:{status:"QUESTIONABLE"},identity:id,caliber:cal,replacementCaliber:70});
t("questionable_not_forced_out",()=>assert.equal(q.unavailable,false));
t("questionable_status_preserved",()=>assert.equal(q.availabilityStatus,"QUESTIONABLE"));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Historical Availability & Player Caliber Foundation",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D1-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
