import assert from "node:assert/strict";import{SOURCE_DOMAINS,adaptNFLHistoricalScheduleResultRecord,adaptNFLHistoricalPerformanceSnapshot,adaptNFLHistoricalWeeklyRoster,adaptNFLHistoricalAvailabilityRecords,createNFLHistoricalPregameEvidenceBundle,assembleNFLHistoricalCalibrationObservation,assembleNFLHistoricalObservationSet}from"../teamIntelligence/strength/calibration/index.js";
const T=[];const t=(n,f)=>{try{f();T.push([n,true])}catch(e){T.push([n,false,e.message])}};
const m={team:"BAL",opponent:"BUF",season:2025,week:1,gameId:"2025_01_BAL_BUF",retrievedAt:"2026-08-13T20:00:00Z",effectiveAt:"2025-09-07T19:00:00Z",kickoffAt:"2025-09-07T20:20:00Z"};
const s=adaptNFLHistoricalScheduleResultRecord({season:2025,week:1,game_id:m.gameId,home_team:"BUF",away_team:"BAL",home_score:20,away_score:24,game_datetime:m.kickoffAt},{team:"BAL",retrievedAt:m.retrievedAt,effectiveAt:m.effectiveAt});
const p=adaptNFLHistoricalPerformanceSnapshot({team:"BAL",opponent:"BUF",season:2025,week:1,offenseEPAperPlay:.1,offenseSuccessRate:.49,defenseEPAperPlayAllowed:-.03,defenseSuccessRateAllowed:.42,recentOffenseEPAperPlay:.14,recentDefenseEPAperPlayAllowed:-.05,sampleGames:8,recentWindowGames:4},m);
const r=adaptNFLHistoricalWeeklyRoster([{team:"BAL",gsis_id:"P1",full_name:"QB One",position:"QB",status:"ACT"},{team:"BAL",gsis_id:"P2",full_name:"WR One",position:"WR",status:"ACT"},{team:"BUF",gsis_id:"P3",position:"QB"}],m);
const a=adaptNFLHistoricalAvailabilityRecords([{team:"BAL",gsis_id:"P1",full_name:"QB One",position:"QB",practice_status:"FP",game_status:"QUESTIONABLE",primary_injury:"Ankle"}],m);
const late=adaptNFLHistoricalPerformanceSnapshot({team:"BAL",opponent:"BUF",season:2025,week:1,offenseEPAperPlay:.99},{...m,effectiveAt:"2025-09-08T00:00:00Z"});
const b=createNFLHistoricalPregameEvidenceBundle([s,p,r,a,late],SOURCE_DOMAINS),o=assembleNFLHistoricalCalibrationObservation(b,{split:"TRAIN"}),set=assembleNFLHistoricalObservationSet([s,p,r,a,late],{split:"TRAIN"});
const checks=[
["schedule",()=>assert.ok(s)],["schedule_domain",()=>assert.equal(s.domain,SOURCE_DOMAINS.SCHEDULES_RESULTS)],["schedule_team",()=>assert.equal(s.team,"BAL")],["schedule_opp",()=>assert.equal(s.opponent,"BUF")],["schedule_final",()=>assert.equal(s.payload.final,true)],["schedule_score",()=>assert.equal(s.payload.teamScore,24)],["schedule_won",()=>assert.equal(s.payload.won,true)],
["performance",()=>assert.ok(p)],["performance_domain",()=>assert.equal(p.domain,SOURCE_DOMAINS.TEAM_STATS)],["epa",()=>assert.equal(p.payload.offenseEPAperPlay,.1)],["success_rate",()=>assert.equal(p.payload.offenseSuccessRate,.49)],["recent_epa",()=>assert.equal(p.payload.recentOffenseEPAperPlay,.14)],["sample_games",()=>assert.equal(p.payload.sampleGames,8)],
["roster",()=>assert.ok(r)],["roster_domain",()=>assert.equal(r.domain,SOURCE_DOMAINS.WEEKLY_ROSTERS)],["roster_filter",()=>assert.equal(r.payload.playerCount,2)],["roster_id",()=>assert.equal(r.payload.players[0].playerId,"P1")],["roster_pos",()=>assert.equal(r.payload.players[0].position,"QB")],
["availability",()=>assert.ok(a)],["availability_domain",()=>assert.equal(a.domain,SOURCE_DOMAINS.INJURIES)],["availability_count",()=>assert.equal(a.payload.playerCount,1)],["availability_status",()=>assert.equal(a.payload.players[0].gameStatus,"QUESTIONABLE")],["availability_injury",()=>assert.equal(a.payload.players[0].reportPrimaryInjury,"Ankle")],
["late_unsafe",()=>assert.equal(late.safeForPregameCalibration,false)],["bundle_version",()=>assert.equal(b.bundleVersion,"FIE-NFL-HISTORICAL-PREGAME-EVIDENCE-BUNDLE-1.0.0")],["bundle_rejects_late",()=>assert.equal(b.rejectedUnsafeCount,1)],["bundle_schedule",()=>assert.equal(b.schedule.sourceId,"NFLVERSE_SCHEDULES")],["bundle_perf",()=>assert.equal(b.performance.sourceId,"NFLVERSE_TEAM_STATS")],["bundle_roster",()=>assert.equal(b.roster.sourceId,"NFLVERSE_WEEKLY_ROSTERS")],["bundle_avail",()=>assert.equal(b.availability.sourceId,"NFLVERSE_INJURIES")],["late_not_selected",()=>assert.equal(b.performance.payload.offenseEPAperPlay,.1)],
["obs",()=>assert.ok(o)],["obs_game",()=>assert.equal(o.gameId,m.gameId)],["obs_team",()=>assert.equal(o.team,"BAL")],["obs_opp",()=>assert.equal(o.opponent,"BUF")],["obs_safe",()=>assert.equal(o.leakageSafe,true)],["obs_split",()=>assert.equal(o.split,"TRAIN")],["obs_final",()=>assert.equal(o.outcome.status,"FINAL")],["obs_diff",()=>assert.equal(o.outcome.pointDifferential,4)],["obs_roster",()=>assert.equal(o.evidence.rosterDepth.playerCount,2)],["obs_avail",()=>assert.equal(o.evidence.availabilityImpact.playerCount,1)],["obs_perf",()=>assert.equal(o.evidence.performance.offenseEPAperPlay,.1)],["obs_recent",()=>assert.equal(o.evidence.recentForm.recentWindowGames,4)],["obs_caliber_null",()=>assert.equal(o.evidence.playerCaliber,null)],["obs_unit_null",()=>assert.equal(o.evidence.unitState,null)],["outcome_prov",()=>assert.deepEqual([...o.provenance.outcomeSourceIds],["NFLVERSE_SCHEDULES"])],["perf_prov",()=>assert.ok(o.provenance.evidenceSourceIds.includes("NFLVERSE_TEAM_STATS"))],["roster_prov",()=>assert.ok(o.provenance.evidenceSourceIds.includes("NFLVERSE_WEEKLY_ROSTERS"))],["avail_prov",()=>assert.ok(o.provenance.evidenceSourceIds.includes("NFLVERSE_INJURIES"))],
["set_version",()=>assert.equal(set.serviceVersion,"FIE-NFL-HISTORICAL-OBSERVATION-ASSEMBLY-SERVICE-1.0.0")],["set_valid",()=>assert.equal(set.status,"VALID")],["set_one",()=>assert.equal(set.observations.length,1)],["set_no_reject",()=>assert.equal(set.rejected.length,0)],["set_weights_null",()=>assert.equal(set.learnedWeights,null)],["set_scores_null",()=>assert.equal(set.teamStrengthScores,null)]];
for(const [n,f]of checks)t(n,f);const bad=T.filter(x=>!x[1]);console.log(JSON.stringify({suite:"NFL Historical Acquisition Adapters & Observation Assembly",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9B-1.0.0",status:bad.length?"FAIL":"PASS",passed:T.length-bad.length,failed:bad.length,checks:Object.fromEntries(T.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));if(bad.length)process.exitCode=1;