import assert from "node:assert/strict";
import {getNFLHistoricalPregameTemporalAnchorGovernance as get} from "../teamIntelligence/strength/calibration/index.js";
const g=get(),tests=[];const t=(n,f)=>{try{f();tests.push([n,true])}catch(e){tests.push([n,false,e.message])}};
t("contract",()=>assert.equal(g.contractVersion,"FIE-NFL-HISTORICAL-PREGAME-TEMPORAL-ANCHOR-GOVERNANCE-1.0.0"));
t("2022",()=>assert.ok(g.targetSeasons.includes(2022)));
t("2023",()=>assert.ok(g.targetSeasons.includes(2023)));
t("2024",()=>assert.ok(g.targetSeasons.includes(2024)));
t("depth_timestamp_can_qualify",()=>assert.equal(g.rules.depthChartTimestampDirectlyQualifies,true));
t("publication_metadata_can_qualify",()=>assert.equal(g.rules.sourcePublicationMetadataMayQualify,true));
t("starter_announcement_can_qualify",()=>assert.equal(g.rules.explicitStarterAnnouncementMayQualify,true));
t("injury_timestamp_not_depth_publication",()=>assert.equal(g.rules.injuryTimestampQualifiesAvailabilityNotDepthChartPublication,true));
t("transaction_not_depth_publication",()=>assert.equal(g.rules.transactionTimestampQualifiesTransactionNotDepthChartPublication,true));
t("snap_not_pregame",()=>assert.equal(g.rules.snapCountTimestampQualifiesPregameReplacement,false));
t("week_scope_not_enough",()=>assert.equal(g.rules.weekScopeAloneQualifiesPregame,false));
t("no_inferred_publication",()=>assert.equal(g.rules.inferredPublicationTimeAllowed,false));
t("no_future_evidence",()=>assert.equal(g.rules.futureEvidenceAllowed,false));
t("ambiguous_stays_unqualified",()=>assert.equal(g.rules.ambiguousTemporalAnchorRemainsUnqualified,true));
t("no_mapping",()=>assert.equal(g.outputPolicy.replacementMappingsGenerated,false));
t("no_mutation",()=>assert.equal(g.outputPolicy.depthChartRowsMutated,false));
t("no_weights",()=>assert.equal(g.outputPolicy.learnedWeightsAuthorized,false));
t("no_calibration",()=>assert.equal(g.outputPolicy.calibrationAuthorized,false));
const bad=tests.filter(x=>!x[1]);
console.log(JSON.stringify({suite:"NFL Historical Pregame Temporal Anchor Governance",contractVersion:"FIE-NFL-TEAM-STRENGTH-CALIBRATION-9D1C2B2A-1.0.0",status:bad.length?"FAIL":"PASS",passed:tests.length-bad.length,failed:bad.length,checks:Object.fromEntries(tests.map(x=>[x[0],x[1]])),failures:bad.map(x=>x[0]+": "+x[2])},null,2));
if(bad.length)process.exitCode=1;
