import assert from "node:assert/strict";
import { NFL_PLAYER_IMPACT_PROMOTION_GATE_2D3 as G } from "../teamIntelligence/strength/calibration/playerEvidence/NFLPlayerImpactPromotionGateGovernance.js";
const tests=[];
const test=(name,fn)=>{try{fn();tests.push({name,passed:true})}catch(e){tests.push({name,passed:false,error:e.message})}};
test("contract",()=>assert.equal(G.contractVersion,"FIE-NFL-PLAYER-IMPACT-PROMOTION-GATE-GOVERNANCE-1.0.1"));
test("team-game-unit",()=>assert.equal(G.unitOfAnalysis,"TREATED_TEAM_GAME_MATCHED_ATT"));
test("att-no-player-id",()=>assert.equal(G.matchedATTContainsIndividualPlayerIdentity,false));
test("no-one-to-one-player-join",()=>assert.equal(G.oneToOnePlayerJoinRequired,false));
test("season-representation-correct",()=>assert.equal(G.allFiveSeasonsRepresentedMeans,"AT_LEAST_ONE_USABLE_MATCHED_EFFECT_PER_SEASON"));
test("25-not-hard-gate",()=>assert.equal(G.minimum25EffectsPerSeasonIsHardGate,false));
test("legacy-131",()=>assert.equal(G.legacyMatchedATTExpectedPairs,131));
test("expansion-not-131",()=>assert.equal(G.expansionMustEqualLegacyCardinality,false));
test("integrity-required",()=>assert.equal(G.expansionStructuralIntegrityRequired,true));
test("targeted-three",()=>assert.equal(G.targetedSensitivityRequired.length,3));
test("reopen-only-hard-failure",()=>assert.equal(G.antiWeedsPolicy.reopenHistoricalConstructionOnlyOnHardIntegrityFailure,true));
test("no-caliper-retune",()=>assert.equal(G.antiWeedsPolicy.doNotRetuneCaliper,true));
test("no-invented-player-id",()=>assert.equal(G.antiWeedsPolicy.doNotInventPlayerIdentityForTeamGameATT,true));
test("no-pickem-weights",()=>assert.equal(G.antiWeedsPolicy.doNotCreateIndependentPickemWeights,true));
test("shadow-only",()=>assert.equal(G.safeguards.mode,"SHADOW_ONLY"));
test("production-fit-blocked",()=>assert.equal(G.safeguards.productionWeightsFitAuthorized,false));
test("calibration-blocked",()=>assert.equal(G.safeguards.calibrationAuthorized,false));
test("team-strength-blocked",()=>assert.equal(G.safeguards.teamStrengthMutationAuthorized,false));
test("decision-model-blocked",()=>assert.equal(G.safeguards.decisionModelMutationAuthorized,false));
test("pickem-blocked",()=>assert.equal(G.safeguards.pickemMutationAuthorized,false));
const passed=tests.filter(t=>t.passed).length,failed=tests.length-passed;
console.log(JSON.stringify({suite:"NFL Player Impact Promotion Gate Governance 1.0.1",status:failed?"FAIL":"PASS",passed,failed,tests},null,2));
if(failed)process.exitCode=1;
