import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
export const DEFAULT_REPLACEMENT_FILE='data/calibration/historical/v1/expected-replacement-identities-caliber-enriched-v1.jsonl';
export const DEFAULT_DECISION_MODULE='src/data/footballIntelligence/nfl/decisionSupport/sources/generatedNFLHistoricalDecisionDataset.js';
export const DEFAULT_OUTPUT='data/calibration/historical/v1/historical-availability-impact-calibration-observations-v1.jsonl';
export const DEFAULT_RESIDUALS='data/calibration/historical/v1/historical-availability-impact-calibration-residuals-v1.jsonl';
export const DEFAULT_REPORT='data/calibration/historical/v1/historical-availability-impact-calibration-observations-v1-report.json';
const num=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null); const str=v=>v==null?null:(String(v).trim()||null); const up=v=>str(v)?.toUpperCase()??null;
const get=(o,keys)=>{for(const k of keys){let v=o;for(const p of k.split('.'))v=v?.[p];if(v!=null)return v}return null};
export const loadJsonl=f=>fs.existsSync(f)?fs.readFileSync(f,'utf8').split(/\r?\n/).filter(Boolean).map(JSON.parse):[];
export async function loadCanonicalDecisionDataset(file=DEFAULT_DECISION_MODULE){const abs=path.resolve(file);if(!fs.existsSync(abs))return{file:abs,records:[],error:'CANONICAL_DECISION_MODULE_NOT_FOUND'};try{const m=await import(pathToFileURL(abs).href);const d=m.generatedNFLHistoricalDecisionDataset??m.default?.generatedNFLHistoricalDecisionDataset??m.default;const records=Array.isArray(d)?d:(Array.isArray(d?.records)?d.records:[]);return{file:abs,records,error:records.length?null:'CANONICAL_DECISION_DATASET_EMPTY_OR_UNRECOGNIZED'}}catch(e){return{file:abs,records:[],error:`CANONICAL_DECISION_MODULE_IMPORT_FAILED: ${e.message}`}}}
export function normalizeDecisionRecord(r={}){return{raw:r,gameId:str(get(r,['gameId','identity.gameId','game.gameId'])),season:num(get(r,['season','identity.season','game.season'])),week:num(get(r,['week','identity.week','game.week'])),gameType:up(get(r,['gameType','identity.gameType','game.gameType'])),awayTeam:up(get(r,['awayTeam','identity.awayTeam','game.awayTeam'])),homeTeam:up(get(r,['homeTeam','identity.homeTeam','game.homeTeam'])),awayScore:num(get(r,['outcome.awayScore','awayScore','game.awayScore'])),homeScore:num(get(r,['outcome.homeScore','homeScore','game.homeScore'])),snapshotThroughWeek:num(get(r,['pregame.snapshotThroughWeek','pregame.features.snapshotThroughWeek','snapshotThroughWeek']))}}
export function indexDecisionRecords(rows=[]){const normalized=rows.map(normalizeDecisionRecord),byGameId=new Map(),bySWT=new Map();for(const r of normalized){if(r.gameId){if(!byGameId.has(r.gameId))byGameId.set(r.gameId,[]);byGameId.get(r.gameId).push(r)}for(const t of [r.awayTeam,r.homeTeam].filter(Boolean)){const k=`${r.season}:${r.week}:${t}`;if(!bySWT.has(k))bySWT.set(k,[]);bySWT.get(k).push(r)}}return{normalized,byGameId,bySWT}}
const identity=p=>({season:num(p.season),week:num(p.week),gameId:str(p.gameId),team:up(p.team),opponent:up(p.opponent),position:up(p.position),unavailablePlayerId:str(p.unavailablePlayerId),replacementPlayerId:str(p.replacementPlayerId)});
export function resolveDecisionRecord(p,idx){const i=identity(p);let c=i.gameId?(idx.byGameId.get(i.gameId)??[]):[];if(!c.length&&i.season!=null&&i.week!=null&&i.team)c=idx.bySWT.get(`${i.season}:${i.week}:${i.team}`)??[];if(i.opponent&&c.length>1)c=c.filter(r=>(r.awayTeam===i.team&&r.homeTeam===i.opponent)||(r.homeTeam===i.team&&r.awayTeam===i.opponent));return c.length===1?{status:'JOINED',record:c[0]}:c.length>1?{status:'AMBIGUOUS',candidates:c.length}:{status:'MISSING',candidates:0}}
export function createObservation(p,d){const i=identity(p),side=d.awayTeam===i.team?'AWAY':d.homeTeam===i.team?'HOME':null;if(!side)return null;const tp=side==='AWAY'?d.awayScore:d.homeScore,op=side==='AWAY'?d.homeScore:d.awayScore,final=Number.isFinite(tp)&&Number.isFinite(op);return{contract:'NFLHistoricalAvailabilityImpactCalibrationObservation',contractVersion:'FIE-NFL-HISTORICAL-AVAILABILITY-IMPACT-CALIBRATION-OBSERVATION-1.0.0',identity:{...i,gameType:d.gameType,gameId:d.gameId,opponent:i.opponent??(side==='AWAY'?d.homeTeam:d.awayTeam)},pregame:{unavailableStatus:p.unavailableStatus??p.status??null,playerCaliber:num(p.playerCaliber),playerCaliberConfidence:num(p.playerCaliberConfidence),replacementCaliber:num(p.replacementCaliber),replacementCaliberConfidence:num(p.replacementCaliberConfidence),expectedReplacementDelta:num(p.expectedReplacementDelta),replacementEvidenceType:p.evidenceType??p.replacementEvidenceType??null,usage:p.usage??p.historicalUsage??null,historicalDecisionPregame:{season:d.season,week:d.week,snapshotThroughWeek:d.snapshotThroughWeek}},outcome:{status:final?'FINAL':'UNAVAILABLE',teamPoints:final?tp:null,opponentPoints:final?op:null,pointMargin:final?tp-op:null,won:final?tp>op:null,tied:final?tp===op:null},calibration:{predictedImpact:null,observedImpact:null,fitAuthorized:false,reason:'OBSERVATION_CONSTRUCTION_ONLY_BASELINE_ADJUSTED_TARGET_NOT_YET_AUTHORIZED'},provenance:{replacementMapping:'expected-replacement-identities-caliber-enriched-v1',historicalDecisionDataset:'generatedNFLHistoricalDecisionDataset.js'},safeguards:{completeCaliberPairRequired:true,pregameCaliberOnly:true,replacementIdentityEvidenceBacked:true,postgameOutcomeUsedOnlyAsTargetEvidence:true,rawPointMarginIsNotObservedPlayerImpact:true}}}
export async function constructHistoricalAvailabilityImpactCalibrationObservations(){const pairs=loadJsonl(DEFAULT_REPLACEMENT_FILE),complete=pairs.filter(p=>up(p.caliberEnrichmentStatus)==='COMPLETE'&&num(p.expectedReplacementDelta)!=null),loaded=await loadCanonicalDecisionDataset(),idx=indexDecisionRecords(loaded.records),observations=[],residuals=[];let joined=0,missing=0,ambiguous=0,invalid=pairs.length-complete.length;for(const p of complete){const r=resolveDecisionRecord(p,idx);if(r.status==='MISSING'){missing++;residuals.push({reason:'MISSING_DECISION_RECORD',pair:p});continue}if(r.status==='AMBIGUOUS'){ambiguous++;residuals.push({reason:'AMBIGUOUS_DECISION_RECORD',candidateCount:r.candidates,pair:p});continue}joined++;const o=createObservation(p,r.record);if(o)observations.push(o);else{invalid++;residuals.push({reason:'TEAM_NOT_PRESENT_IN_JOINED_DECISION_RECORD',pair:p})}}const byPosition={};let withUsage=0;for(const o of observations){const p=o.identity.position??'UNKNOWN';byPosition[p]=(byPosition[p]??0)+1;if(o.pregame.usage)withUsage++}return{loaded,observations,residuals,report:{contractVersion:'FIE-NFL-HISTORICAL-AVAILABILITY-IMPACT-CALIBRATION-OBSERVATION-REPORT-1.0.1',sprint:'2.18.8-RC2',decisionDatasetFile:loaded.file,decisionDatasetImportError:loaded.error,canonicalDecisionRecords:loaded.records.length,replacementPairs:pairs.length,completeInputCount:complete.length,joinedDecisionRecordCount:joined,observationCount:observations.length,missingDecisionRecordCount:missing,ambiguousDecisionRecordCount:ambiguous,invalidInputCount:invalid,observationCoverage:complete.length?observations.length/complete.length:0,withUsage,byPosition,readiness:{sufficientObservationVolumeForFormalFitting:observations.length>=200,observedImpactTargetDefined:false,formalFittingAuthorized:false},safeguards:{canonicalHistoricalDecisionDatasetMutated:false,enrichedReplacementDatasetMutated:false,historicalPregameSnapshotsMutated:false,currentRatingBackfillUsed:false,currentRecognitionBackfillUsed:false,targetWeekLeakageIntroduced:false,futureEvidenceUsed:false,learnedWeightsCreated:false,calibrationExecuted:false,observedImpactFabricated:false,decisionModelMutated:false,teamStrengthMutated:false,pickemScoringMutated:false,databaseMutated:false}}}}
