import assert from "node:assert/strict";
import { createSportradarNFLAvailabilityProviderAdapter, adaptSportradarWeeklyInjuriesPayload, SPORTRADAR_NFL_AVAILABILITY_PROVIDER_ID } from "../src/data/footballIntelligence/nfl/availability/providers/sportradar/SportradarNFLAvailabilityProviderAdapter.js";
import { DEFAULT_NFL_AVAILABILITY_PROVIDER_REGISTRY } from "../src/data/footballIntelligence/nfl/availability/providers/NFLAvailabilityProviderRegistry.js";
import { orchestrateNFLAvailabilityProviders } from "../src/data/footballIntelligence/nfl/availability/providers/NFLAvailabilityProviderOrchestrator.js";
const tests=[]; async function test(name,fn){try{await fn();tests.push({name,passed:true});}catch(e){tests.push({name,passed:false,error:e.message});}}

const nestedFixture={season:{year:2025},week:{sequence:1},teams:[{id:"team-bal",alias:"BAL",players:[{id:"sr-player-1",name:"Example Quarterback",position:"QB",status:"Out",status_date:"2099-01-01T00:00:00Z",practice:{status:"Full"},estimated_return_date:"2025-09-15",injuries:[{primary:"Hamstring",status:"Questionable",status_date:"2025-09-05T00:00:00+00:00",practice:{status:"Limited Participation In Practice"}}]}]}]};
const missingTimestampFixture={teams:[{id:"team-car",alias:"CAR",players:[{id:"sr-player-2",name:"Example Defender",position:"LB",injuries:[{primary:"Knee",status:"Doubtful",practice:{status:"Did Not Participate In Practice"}}]}]}]};
const legacyFixture={generated_at:"2026-08-13T12:00:00Z",teams:[{id:"team-bal",alias:"BAL",players:[{id:"sr-player-3",name:"Legacy Shape",position:"QB",status:"Questionable",status_date:"2026-08-13T11:30:00Z",practice:{status:"Limited"},injuries:[{primary:true,description:"Hamstring"}]}]}]};

await test("sportradar-primary-is-highest-priority",()=>assert.equal(DEFAULT_NFL_AVAILABILITY_PROVIDER_REGISTRY.providers[0].id,SPORTRADAR_NFL_AVAILABILITY_PROVIDER_ID));
await test("weekly-injury-payload-normalizes",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1,sourceUrl:"https://example.test"});assert.equal(r.team,"BAL");assert.equal(r.player.position,"QB");});
await test("nested-report-status-normalizes",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.status.report,"QUESTIONABLE");});
await test("nested-practice-status-normalizes",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.status.practice,"LIMITED_PARTICIPATION_IN_PRACTICE");});
await test("nested-status-date-preserved",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.provenance.modifiedAt,"2025-09-05T00:00:00+00:00");});
await test("nested-temporal-field-provenance-preserved",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.provenance.sourceTemporalField,"injuries[].status_date");assert.equal(r.provenance.sourceTemporalClassification,"PROVIDER_SOURCE_TIME");});
await test("injury-level-status-wins-over-obsolete-player-level-status",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.status.report,"QUESTIONABLE");assert.notEqual(r.status.report,"OUT");});
await test("injury-level-time-wins-over-obsolete-player-level-time",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.provenance.modifiedAt,"2025-09-05T00:00:00+00:00");});
await test("missing-provider-time-remains-null",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(missingTimestampFixture,{season:2025,week:1,now:"2026-08-22T00:00:00Z"});assert.equal(r.provenance.modifiedAt,null);assert.equal(r.provenance.sourceTemporalClassification,"UNAVAILABLE");});
await test("acquisition-time-not-substituted-into-evidence-provenance",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(missingTimestampFixture,{season:2025,week:1,now:"2026-08-22T00:00:00Z"});assert.notEqual(r.provenance.modifiedAt,"2026-08-22T00:00:00Z");});
await test("legacy-player-level-shape-remains-compatible",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(legacyFixture,{season:2026,week:1});assert.equal(r.status.report,"QUESTIONABLE");assert.equal(r.provenance.modifiedAt,"2026-08-13T11:30:00Z");});
await test("provider-player-id-preserved",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.provenance.providerPlayerId,"sr-player-1");});
await test("provider-team-id-preserved",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.provenance.providerTeamId,"team-bal");});
await test("estimated-return-date-preserved",()=>{const [r]=adaptSportradarWeeklyInjuriesPayload(nestedFixture,{season:2025,week:1});assert.equal(r.provenance.estimatedReturnDate,"2025-09-15");});
await test("missing-key-fails-closed",async()=>{const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"",fetchImpl:async()=>{throw new Error("should-not-fetch")}});assert.equal((await a.acquire({season:2025,week:1})).reason,"SPORTRADAR_API_KEY_MISSING");});
await test("season-week-required",async()=>{const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"test",fetchImpl:async()=>{}});assert.equal((await a.acquire({season:2025})).reason,"SEASON_WEEK_REQUIRED");});
await test("x-api-key-header-used",async()=>{let h;const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"secret",fetchImpl:async(u,o)=>{h=o.headers;return {ok:true,json:async()=>nestedFixture}}});await a.acquire({season:2025,week:1});assert.equal(h["x-api-key"],"secret");});
await test("trial-v7-weekly-injuries-url",async()=>{let u;const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"secret",fetchImpl:async(url)=>{u=url;return {ok:true,json:async()=>nestedFixture}}});await a.acquire({season:2025,week:1});assert.match(u,/official\/trial\/v7\/en\/seasons\/2025\/REG\/1\/injuries\.json$/);});
await test("http-error-is-explicit",async()=>{const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"secret",fetchImpl:async()=>({ok:false,status:401})});await assert.rejects(()=>a.acquire({season:2025,week:1}),/SPORTRADAR_HTTP_401/);});
await test("empty-payload-unavailable",async()=>{const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"secret",fetchImpl:async()=>({ok:true,json:async()=>({teams:[]})})});assert.equal((await a.acquire({season:2025,week:1,now:"2026-08-22T00:00:00Z"})).available,false);});
await test("aggregate-observed-at-separates-acquisition-fallback",async()=>{const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"secret",fetchImpl:async()=>({ok:true,json:async()=>missingTimestampFixture})});const r=await a.acquire({season:2025,week:1,now:"2026-08-22T00:00:00Z"});assert.equal(r.observedAt,"2026-08-22T00:00:00Z");assert.equal(r.provenance.sourceObservedAt,null);assert.equal(r.provenance.acquiredAt,"2026-08-22T00:00:00Z");assert.equal(r.provenance.observedAtClassification,"ACQUISITION_TIME_FALLBACK");assert.equal(r.records[0].provenance.modifiedAt,null);});
await test("aggregate-observed-at-prefers-provider-time",async()=>{const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"secret",fetchImpl:async()=>({ok:true,json:async()=>nestedFixture})});const r=await a.acquire({season:2025,week:1,now:"2026-08-22T00:00:00Z"});assert.equal(r.observedAt,"2025-09-05T00:00:00+00:00");assert.equal(r.provenance.observedAtClassification,"PROVIDER_SOURCE_TIME");});
await test("orchestrator-selects-sportradar",async()=>{const a=createSportradarNFLAvailabilityProviderAdapter({apiKey:"secret",fetchImpl:async()=>({ok:true,json:async()=>nestedFixture})});const r=await orchestrateNFLAvailabilityProviders({registry:DEFAULT_NFL_AVAILABILITY_PROVIDER_REGISTRY,adapters:{[SPORTRADAR_NFL_AVAILABILITY_PROVIDER_ID]:a},request:{season:2025,week:1,now:"2025-09-05T01:00:00Z"}});assert.equal(r.selection.provider.id,SPORTRADAR_NFL_AVAILABILITY_PROVIDER_ID);assert.equal(r.persistenceAuthorized,false);});

const failed=tests.filter(x=>!x.passed);console.log(JSON.stringify({suite:"Sportradar NFL Availability Provider Historical Temporal Semantics Diagnostics",passed:tests.length-failed.length,failed:failed.length,tests},null,2));if(failed.length)process.exitCode=1;
