import { execFileSync } from "node:child_process";
import path from "node:path";
const AUDIT=path.resolve("./scripts/auditHistoricalPositionRoleDependencySensitivity.mjs");
const report=JSON.parse(execFileSync(process.execPath,[AUDIT],{cwd:process.cwd(),encoding:"utf8",stdio:["ignore","pipe","pipe"],maxBuffer:64*1024*1024}));
const tests=[];const t=(name,pass)=>tests.push({name,pass:!!pass});
t("131 matched effects present",report?.source?.matchedEffectCount===131);
t("all matched effects reconcile",report?.reconciliation?.allMatchedEffectsReconciled===true);
t("no observation joins missing",report?.reconciliation?.missingObservationJoin===0);
t("no replacement joins missing",report?.reconciliation?.missingReplacementJoin===0);
t("depth rank complete for matched players",report?.reconciliation?.missingDepthRank===0);
t("single-absence cohort populated",report?.source?.singleAbsenceCount>0);
t("QB position family populated",report?.descriptive?.byPositionFamily?.QB?.count>0);
t("OL position family populated",report?.descriptive?.byPositionFamily?.OL?.count>0);
t("skill position family populated",report?.descriptive?.byPositionFamily?.SKILL?.count>0);
t("front seven family populated",report?.descriptive?.byPositionFamily?.FRONT7?.count>0);
t("secondary family populated",report?.descriptive?.byPositionFamily?.SECONDARY?.count>0);
t("position results remain descriptive",report?.interpretation?.positionSignalIsDescriptiveOnly===true);
t("depth-rank role proxy populated",report?.evidenceCoverage?.depthRankRecordCount>0);
t("depth-rank 1 populated",report?.evidenceCoverage?.depthRank1Count>0);
t("depth-rank 2 populated",report?.evidenceCoverage?.depthRank2Count>0);
t("role proxy remains descriptive",report?.interpretation?.depthRankRoleSignalIsDescriptiveOnly===true);
t("single absence group populated",report?.descriptive?.byAbsenceCount?.["1"]?.count>0);
t("two-player absence group populated",report?.descriptive?.byAbsenceCount?.["2"]?.count>0);
t("three-player absence group populated",report?.descriptive?.byAbsenceCount?.["3"]?.count>0);
t("four-player absence group populated",report?.descriptive?.byAbsenceCount?.["4"]?.count>0);
t("multi-absence results remain descriptive",report?.interpretation?.multipleAbsenceSignalIsDescriptiveOnly===true);
t("OUT status populated",report?.descriptive?.byStatus?.OUT?.count>0);
t("DOUBTFUL status populated",report?.descriptive?.byStatus?.DOUBTFUL?.count>0);
t("historical usage is absent rather than fabricated",report?.evidenceCoverage?.historicalUsagePresentCount===0);
t("historical dependency is absent rather than fabricated",report?.evidenceCoverage?.historicalTeamDependencyPresentCount===0);
t("dependency sensitivity explicitly not testable",report?.evidenceCoverage?.dependencySensitivityTestable===false);
t("snap-share sensitivity explicitly not testable",report?.evidenceCoverage?.snapShareSensitivityTestable===false);
t("dependency signal not estimated",report?.interpretation?.dependencySignalNotEstimated===true);
t("snap-share signal not estimated",report?.interpretation?.snapShareSignalNotEstimated===true);
t("historical dependency completion required",report?.readiness?.historicalDependencyEvidenceCompletionRequired===true);
t("full transformation not ready for holdout",report?.readiness?.fullPlayerImpactTransformationReadyForHoldout===false);
t("position coefficient remains unauthorized",report?.safeguards?.positionCoefficientAuthorized===false);
t("role coefficient remains unauthorized",report?.safeguards?.roleCoefficientAuthorized===false);
t("dependency coefficient remains unauthorized",report?.safeguards?.dependencyCoefficientAuthorized===false);
t("team strength value remains unauthorized",report?.safeguards?.teamStrengthPointValueAuthorized===false);
t("team strength remains unmutated",report?.safeguards?.teamStrengthMutated===false);
t("decision model remains unmutated",report?.safeguards?.decisionModelMutated===false);
t("Pick'em remains unmutated",report?.safeguards?.pickemScoringMutated===false);
t("shadow-only boundary preserved",report?.safeguards?.shadowOnlyPreserved===true);
t("decision holds shadow",report?.decision==="POSITION_ROLE_SIGNAL_DESCRIPTIVE_DEPENDENCY_EVIDENCE_BLOCKED_HOLD_SHADOW");
let pass=0;for(const x of tests){console.log(`${x.pass?"PASS":"FAIL"} ${x.name}`);if(x.pass)pass++;}
const fail=tests.length-pass;console.log(`\nHistorical Position / Role / Dependency Sensitivity diagnostics: ${pass}/${tests.length} passed; ${fail} failed.`);
console.log(report?.decision||"NO_DECISION");
if(fail) process.exitCode=2;
