import assert from "node:assert/strict";
import { createNFLAvailabilitySignal, NFL_AVAILABILITY_AUTHORITY, NFL_AVAILABILITY_SIGNAL_CLASSES } from "../src/data/footballIntelligence/nfl/availability/signals/NFLAvailabilitySignalContract.js";
import { createNFLMultiSignalAvailabilityResearchBundle, normalizedNFLAvailabilitySignalSnapshot } from "../src/data/footballIntelligence/nfl/availability/research/NFLMultiSignalAvailabilityResearchCapture.js";
const tests=[]; const test=(name,fn)=>{try{fn();tests.push({name,passed:true});}catch(e){tests.push({name,passed:false,error:e.message});}};
const base={season:2026,week:1,gameType:"PRE",team:"BAL",playerId:"p1",playerName:"Player One",position:"QB",observedAt:"2026-08-13T12:00:00Z",source:"sportradar-test",sourceUrl:"https://example.test/feed"};
const roster=createNFLAvailabilitySignal({...base,signalClass:NFL_AVAILABILITY_SIGNAL_CLASSES.ROSTER_STATUS,authority:NFL_AVAILABILITY_AUTHORITY.ROSTER,rosterStatus:"ACT"});
const depth=createNFLAvailabilitySignal({...base,signalClass:NFL_AVAILABILITY_SIGNAL_CLASSES.DEPTH_CHART,authority:NFL_AVAILABILITY_AUTHORITY.ROLE,depthPosition:"QB",depthRank:1,starter:true});
const tx=createNFLAvailabilitySignal({...base,signalClass:NFL_AVAILABILITY_SIGNAL_CLASSES.TRANSACTION,authority:NFL_AVAILABILITY_AUTHORITY.TRANSACTION,transactionType:"ACT",statusBefore:"PUP",statusAfter:"ACT",effectiveAt:"2026-08-13T10:00:00Z"});
const official=createNFLAvailabilitySignal({...base,signalClass:NFL_AVAILABILITY_SIGNAL_CLASSES.OFFICIAL_INJURY_REPORT,authority:NFL_AVAILABILITY_AUTHORITY.OFFICIAL,status:"QUESTIONABLE",practiceStatus:"LIMITED",injury:"Ankle"});
const bundle=createNFLMultiSignalAvailabilityResearchBundle([roster,depth,tx,official],{checkedAt:"2026-08-13T13:00:00Z"});
test("four-signal-classes-preserved",()=>assert.deepEqual(bundle.summary.signalClasses,["DEPTH_CHART","OFFICIAL_INJURY_REPORT","ROSTER_STATUS","TRANSACTION"]));
test("one-observation-per-signal",()=>assert.equal(bundle.observations.length,4));
test("team-artifact-created",()=>assert.equal(bundle.artifacts.length,1));
test("distinct-multisignal-evidence-id",()=>assert.match(bundle.artifacts[0].evidenceId,/evidence:nfl-multisignal-availability/));
test("signal-class-tagged",()=>assert.ok(bundle.observations.every(o=>o.metadata.tags.some(t=>t.startsWith("signal:")))));
test("authority-tagged",()=>assert.ok(bundle.observations.every(o=>o.metadata.tags.some(t=>t.startsWith("authority:")))));
test("provider-provenance-preserved",()=>assert.ok(bundle.observations.every(o=>o.metadata.tags.includes("provider:sportradar-test"))));
test("official-remains-distinct",()=>{const x=JSON.parse(bundle.observations.find(o=>o.metadata.tags.includes("signal:OFFICIAL_INJURY_REPORT")).record.valueText);assert.equal(x.availability.status,"QUESTIONABLE");assert.equal(x.availability.rosterStatus,null);});
test("roster-remains-distinct",()=>{const x=JSON.parse(bundle.observations.find(o=>o.metadata.tags.includes("signal:ROSTER_STATUS")).record.valueText);assert.equal(x.availability.rosterStatus,"ACT");assert.equal(x.availability.status,null);});
test("depth-role-preserved",()=>{const x=JSON.parse(bundle.observations.find(o=>o.metadata.tags.includes("signal:DEPTH_CHART")).record.valueText);assert.equal(x.role.depthRank,1);assert.equal(x.role.starter,true);});
test("transaction-transition-preserved",()=>{const x=JSON.parse(bundle.observations.find(o=>o.metadata.tags.includes("signal:TRANSACTION")).record.valueText);assert.equal(x.transaction.statusBefore,"PUP");assert.equal(x.transaction.statusAfter,"ACT");});
test("idempotency-excludes-acquisition-observedAt",()=>{const later={...roster,timing:{...roster.timing,observedAt:"2026-08-13T14:00:00Z"}};const a=createNFLMultiSignalAvailabilityResearchBundle([roster]);const b=createNFLMultiSignalAvailabilityResearchBundle([later]);assert.equal(a.observations[0].observationId,b.observations[0].observationId);assert.equal(a.artifacts[0].metadata.externalRefs.find(x=>x.startsWith("content-hash:")),b.artifacts[0].metadata.externalRefs.find(x=>x.startsWith("content-hash:")));});
test("content-change-creates-new-observation",()=>{const changed={...roster,availability:{...roster.availability,rosterStatus:"IR"}};const a=createNFLMultiSignalAvailabilityResearchBundle([roster]);const b=createNFLMultiSignalAvailabilityResearchBundle([changed]);assert.notEqual(a.observations[0].observationId,b.observations[0].observationId);});
test("no-raw-api-payload-storage",()=>assert.equal(bundle.source.usageRestrictions.rawContentStorageAllowed,false));
test("no-fid-ownership",()=>assert.ok(!JSON.stringify(bundle).includes("ProspectIntake")&&!JSON.stringify(bundle).includes("FID_ATOMIC")));
console.log(JSON.stringify({suite:"Live Multi-Signal Availability Persistence V1 Diagnostics",passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,tests},null,2)); if(tests.some(t=>!t.passed)) process.exitCode=1;
