import path from "node:path";
import {execFileSync} from "node:child_process";

const output=execFileSync(process.execPath,[path.resolve("./scripts/auditPlayerImpactHoldoutSensitivityPromotionGate.mjs")],{encoding:"utf8"});
const r=JSON.parse(output), tests=[];
const test=(name,passed)=>tests.push({name,passed:Boolean(passed)});

test("286 historical observations retained",r.evidence.observations===286);
test("131 matched effects retained",r.evidence.matchedEffects===131);
test("286 usage records retained",r.evidence.usageEvidenceRecords===286);
test("31 matched dependency records retained",r.evidence.matchedDependencyCount===31);
test("Sprint 5 HOLD status consumed",r.evidence.sprint5Decision==="MULTIVARIATE_PLAYER_IMPACT_SIGNAL_NOT_YET_STABLE_HOLD_SHADOW");
test("Sprint 6 HOLD status consumed",r.evidence.sprint6Decision==="TEMPORAL_PLAYER_IMPACT_SIGNAL_NOT_ESTABLISHED_ERA_COVERAGE_INSUFFICIENT_HOLD_SHADOW");
test("lineage hard gate passes",r.hardGates.lineageComplete===true);
test("Sprint 5 signal hard gate fails",r.hardGates.sprint5MultivariateSignalSupported===false);
test("chronological stability hard gate fails",r.hardGates.chronologicalCoreStable===false);
test("season interaction stability hard gate fails",r.hardGates.interactionStableAcrossSeasons===false);
test("era validation hard gate fails",r.hardGates.eraValidationSatisfied===false);
test("five-season coverage hard gate fails",r.hardGates.minimumFiveSeasonCoverage===false);
test("dependency coverage hard gate fails",r.hardGates.dependencyCoverageAtLeastHalf===false);
test("threshold grid executes",r.sensitivity.cells.length===9);
test("threshold sensitivity is not falsely declared robust",r.hardGates.thresholdSensitivityRobust===false);
test("promotion is not authorized",r.gateSummary.promotionAuthorized===false);
test("decision is HOLD_SHADOW_AND_REQUIRE_EVIDENCE_EXPANSION",r.decision==="HOLD_SHADOW_AND_REQUIRE_EVIDENCE_EXPANSION");
test("at least one hard gate passes",r.gateSummary.passedHardGates>=1);
test("multiple hard gates fail",r.gateSummary.failedHardGates.length>=5);
test("evidence expansion requirements emitted",r.evidenceExpansionRequirements.length===5);
test("season expansion required",r.evidenceExpansionRequirements.some(x=>x.id==="EXPAND_SEASON_COVERAGE"&&x.required));
test("dependency expansion required",r.evidenceExpansionRequirements.some(x=>x.id==="IMPROVE_DEPENDENCY_COVERAGE"&&x.required));
test("predeclared specification required",r.evidenceExpansionRequirements.some(x=>x.id==="PRESERVE_PREDECLARED_SPECIFICATION"&&x.required));
test("new out-of-time holdout required",r.evidenceExpansionRequirements.some(x=>x.id==="NEW_OUT_OF_TIME_HOLDOUT"&&x.required));
test("sensitivity gate repeat required",r.evidenceExpansionRequirements.some(x=>x.id==="REPEAT_SENSITIVITY_GATE"&&x.required));
test("promotion gate complete",r.readiness.promotionGateComplete===true);
test("Sprint 8 is not authorized",r.readiness.sprint8ShadowTransformationAuthorized===false);
test("next program is evidence expansion",r.readiness.recommendedNextProgram==="PLAYER_IMPACT_EVIDENCE_EXPANSION_PROGRAM");
test("calibration remains unauthorized",r.readiness.calibrationAuthorized===false);
test("production policy remains unauthorized",r.readiness.productionImpactPolicyAuthorized===false);
test("prior thresholds not refit",r.safeguards.priorSprintThresholdsRefit===false);
test("holdout not used for refit",r.safeguards.holdoutDataUsedForRefit===false);
test("source datasets unmutated",r.safeguards.sourceDatasetsMutated===false);
test("matched design unmutated",r.safeguards.matchedDesignMutated===false);
test("causal estimand unmutated",r.safeguards.causalEstimandMutated===false);
test("learned production weight not created",r.safeguards.learnedProductionWeightCreated===false);
test("player coefficient unauthorized",r.safeguards.playerCoefficientAuthorized===false);
test("position coefficient unauthorized",r.safeguards.positionCoefficientAuthorized===false);
test("dependency coefficient unauthorized",r.safeguards.dependencyCoefficientAuthorized===false);
test("Team Strength point value unauthorized",r.safeguards.teamStrengthPointValueAuthorized===false);
test("Team Strength unmutated",r.safeguards.teamStrengthMutated===false);
test("Decision Model unmutated",r.safeguards.decisionModelMutated===false);
test("Pick'em unmutated",r.safeguards.pickemScoringMutated===false);
test("database unmutated",r.safeguards.databaseMutated===false);
test("shadow-only boundary preserved",r.safeguards.shadowOnlyPreserved===true);

for(const t of tests) console.log(`${t.passed?"PASS":"FAIL"} ${t.name}`);
const passed=tests.filter(t=>t.passed).length,failed=tests.length-passed;
console.log(`\nPlayer Impact Holdout + Sensitivity Promotion Gate diagnostics: ${passed}/${tests.length} passed; ${failed} failed.`);
console.log(r.decision);
if(failed) process.exitCode=1;
