import {execFileSync} from "node:child_process";
import path from "node:path";
const out=execFileSync(process.execPath,[path.resolve("./scripts/auditTemporalSeasonEraPlayerImpactValidation.mjs")],{encoding:"utf8"});
const r=JSON.parse(out),t=[];const test=(n,p)=>t.push({n,p:Boolean(p)});
test("286 historical observations retained",r.source.observationCount===286);
test("131 matched effects retained",r.source.matchedEffectCount===131);
test("286 usage evidence records retained",r.source.usageEvidenceCount===286);
test("131 temporal validation rows built",r.source.validationRowCount===131);
test("zero missing joins",r.source.missingJoinCount===0);
test("2022 season present",Boolean(r.seasonStability.bySeason["2022"]));
test("2023 season present",Boolean(r.seasonStability.bySeason["2023"]));
test("2024 season present",Boolean(r.seasonStability.bySeason["2024"]));
test("three interaction-eligible seasons",r.seasonStability.interactionEligibleSeasonCount===3);
test("interaction direction is not falsely declared perfectly stable",r.seasonStability.interactionDirectionConsistency<1);
test("2022 interaction reverses expected direction",r.seasonStability.bySeason["2022"].interactionDirectionExpected===false);
test("2023 interaction has expected direction",r.seasonStability.bySeason["2023"].interactionDirectionExpected===true);
test("2024 interaction has expected direction",r.seasonStability.bySeason["2024"].interactionDirectionExpected===true);
test("two chronological tests executed",r.chronologicalValidation.tests.length===2);
test("2022 to 2023 chronology present",r.chronologicalValidation.tests[0].testSeason===2023);
test("2022-2023 to 2024 chronology present",r.chronologicalValidation.tests[1].testSeason===2024);
test("chronological validation not misclassified as passed",r.chronologicalValidation.allCoreTestsImproveOverIntercept===false);
test("era validation identifies only three seasons",r.eraValidation.seasonCount===3);
test("era validation requires at least five seasons",r.eraValidation.requestedMinimumSeasonCount===5);
test("multi-era coverage unavailable",r.eraValidation.multipleEraCoverageAvailable===false);
test("era status explicit",r.eraValidation.status==="INSUFFICIENT_ERA_COVERAGE");
test("temporal signal remains unestablished",r.interpretation.temporalSignalEstablished===false);
test("interaction stability remains false",r.interpretation.highUsageLargeCaliberInteractionStableAcrossAllEligibleSeasons===false);
test("era validation remains unsatisfied",r.interpretation.eraValidationSatisfied===false);
test("no production coefficient authorized",r.interpretation.noProductionCoefficientAuthorized===true);
test("validation sprint completed",r.readiness.temporalSeasonEraValidationComplete===true);
test("promotion gate may advance as HOLD decision",r.readiness.holdoutSensitivityPromotionGateMayAdvance===true);
test("promotion recommendation HOLD_SHADOW",r.readiness.promotionRecommendation==="HOLD_SHADOW");
test("calibration unauthorized",r.readiness.calibrationAuthorized===false);
test("production policy unauthorized",r.readiness.productionImpactPolicyAuthorized===false);
test("shadow transformation unauthorized",r.readiness.shadowTeamStrengthTransformationAuthorized===false);
test("test-season thresholds not refit",r.safeguards.thresholdsRefitOnTestSeason===false);
test("source datasets unmutated",r.safeguards.sourceDatasetsMutated===false);
test("matched design unmutated",r.safeguards.matchedDesignMutated===false);
test("causal estimand unmutated",r.safeguards.causalEstimandMutated===false);
test("learned production weight not created",r.safeguards.learnedProductionWeightCreated===false);
test("Team Strength unmutated",r.safeguards.teamStrengthMutated===false);
test("Decision Model unmutated",r.safeguards.decisionModelMutated===false);
test("Pick'em unmutated",r.safeguards.pickemScoringMutated===false);
test("database unmutated",r.safeguards.databaseMutated===false);
test("shadow-only preserved",r.safeguards.shadowOnlyPreserved===true);
for(const x of t)console.log(`${x.p?"PASS":"FAIL"} ${x.n}`);
const p=t.filter(x=>x.p).length,f=t.length-p;
console.log(`\nTemporal / Season / Era Player-Impact Validation diagnostics: ${p}/${t.length} passed; ${f} failed.`);
console.log(r.decision);
if(f)process.exitCode=1;
