import pg from "pg";
import { createPostgresResearchRepositoryAdapter } from "../src/data/researchRepository/persistence/postgres/createPostgresResearchRepositoryAdapter.js";
import { PERSISTENCE_CONSISTENCY_MODES,PERSISTENCE_OPERATION_STATUSES,PERSISTENCE_OPERATION_TYPES,PERSISTENCE_RECORD_TYPES } from "../src/data/researchRepository/persistence/index.js";
import { getNFLMultiSignalAvailabilityEvidenceId } from "../src/data/footballIntelligence/nfl/availability/research/NFLMultiSignalAvailabilityResearchCapture.js";
import { projectNFLCanonicalAvailabilityFromMultiSignalResearchSnapshot } from "../src/data/footballIntelligence/nfl/availability/research/NFLCanonicalAvailabilityResearchProjection.js";
import { resolveNFLPlayerImpactIntegratedInputs } from "../src/engines/playerAvailability/integration/NFLPlayerImpactContextInputIntegrationService.js";
const args=process.argv.slice(2);const value=(flag,fallback=null)=>{const i=args.indexOf(flag);return i>=0&&args[i+1]?args[i+1]:fallback;};
const season=Number(value("--season","2026"));const week=Number(value("--week","1"));const gameType=String(value("--game-type","PRE")).toUpperCase();const team=String(value("--team","BAL")).toUpperCase();const playerName=String(value("--player","Lamar Jackson"));
const databaseUrl=process.env.RESEARCH_REPOSITORY_DATABASE_URL;if(!databaseUrl)throw new Error("RESEARCH_REPOSITORY_DATABASE_URL is required.");
const pool=new pg.Pool({connectionString:databaseUrl,ssl:{rejectUnauthorized:false}});const adapter=createPostgresResearchRepositoryAdapter({pool,options:{allowSoftDelete:false,allowArchive:false,allowHardDelete:false}});const success=r=>r?.status===PERSISTENCE_OPERATION_STATUSES.SUCCESS;const read=(recordType,recordId,requestId)=>adapter.read({requestId,operation:PERSISTENCE_OPERATION_TYPES.READ,recordType,recordId,query:{includeArchived:false,includeDeleted:false},consistency:PERSISTENCE_CONSISTENCY_MODES.STANDARD,context:{source:"LIVE_IMPACT_INPUT_INTEGRATION_ACCEPTANCE"}});
try{const evidenceId=getNFLMultiSignalAvailabilityEvidenceId(season,gameType,week,team);const ar=await read(PERSISTENCE_RECORD_TYPES.EVIDENCE_ARTIFACT,evidenceId,`impact-input-artifact:${evidenceId}`);if(!success(ar)||!ar.record)throw new Error(`Active artifact not found: ${evidenceId}`);const artifact=ar.record;const refs=Array.isArray(artifact.recordedObservationRefs)?artifact.recordedObservationRefs:[];const observations=[];for(const ref of refs){const r=await read(PERSISTENCE_RECORD_TYPES.RECORDED_OBSERVATION,ref,`impact-input-observation:${ref}`);if(success(r)&&r.record)observations.push(r.record);}const projected=projectNFLCanonicalAvailabilityFromMultiSignalResearchSnapshot({artifact,observations,season,week,gameType,team});const roster=projected?.resolution?.players||[];const player=roster.find(p=>String(p?.player?.playerName||"").toLowerCase()===playerName.toLowerCase())||null;if(!player)throw new Error(`Player not found: ${playerName}`);const integrated=resolveNFLPlayerImpactIntegratedInputs({canonicalAvailabilityPlayer:player,canonicalAvailabilityRoster:roster,season,week,team});console.log(JSON.stringify({acceptance:"LIVE_CANONICAL_CALIBER_USAGE_TEAM_DEPENDENCY_INTEGRATION",mode:"READ_ONLY",status:"PASS",scope:{season,gameType,week,team,playerName},repository:{evidenceId,observationRefCount:refs.length,observationsResolved:observations.length},canonicalAvailability:{status:player.canonicalAvailabilityStatus,starter:player?.role?.starter??null,depthPosition:player?.role?.depthPosition??null,depthRank:player?.role?.depthRank??null},integratedInputs:{canonicalCaliber:integrated.canonicalCaliber,replacement:integrated.replacement,replacementCaliber:integrated.replacementCaliber,usageEvidence:integrated.usageEvidence,teamDependencyEvidence:integrated.teamDependencyEvidence,contextReadiness:integrated.readiness,missingDimensions:integrated.missingDimensions,context:integrated.contextResolution?.context||null},interpretation:{numericImpactAuthorized:integrated.readiness==="READY",note:integrated.readiness==="READY"?"All context dimensions are available.":"Canonical caliber and usage are integrated. Team dependency remains unresolved and blocks numeric impact."},safeguards:{databaseMutationMethodsInvoked:false,impactScoringInvoked:false,predictionScoringInvoked:false,teamDependencyInvented:false}},null,2));}finally{await pool.end();}
