export const NFL_DECISION_PLAYER_IMPACT_EXPLAINABILITY_GOVERNANCE =
Object.freeze({
  contractVersion:
    "FIE-NFL-DECISION-PLAYER-IMPACT-EXPLAINABILITY-GOVERNANCE-1.0.0",
  sprint: "2D.5B",
  purpose:
    "Add a backward-compatible, read-only canonical explainability projection for availabilityIntelligence.playerAdjustments.",
  existingBoundary: Object.freeze({
    availabilityNamespace: "availabilityIntelligence",
    playerAdjustmentField: "playerAdjustments",
    baselineFieldsMustRemainBackwardCompatible: true,
    pickemMayContinueReadingExistingDecisionFields: true,
  }),
  requestedFields: Object.freeze([
    "playerId",
    "playerName",
    "team",
    "position",
    "role",
    "availabilityStatus",
    "playerCaliberTier",
    "expectedReplacementPlayerId",
    "expectedReplacementName",
    "expectedReplacementCaliberTier",
    "replacementGap",
    "teamDependency",
    "positionImportance",
    "basePlayerImpact",
    "adjustedPlayerImpact",
    "availabilityImpactDelta",
    "policyVersion",
  ]),
  canonicalProjectionRules: Object.freeze({
    missingValuesRemainNull: true,
    presentationLayerMayInferCaliber: false,
    presentationLayerMayInferReplacementQuality: false,
    presentationLayerMayCalculateReplacementGap: false,
    presentationLayerMayInventPositionImportance: false,
    presentationLayerMayRecalculatePlayerImpact: false,
    presentationLayerMayReapplyAvailabilityMath: false,
  }),
  ownership: Object.freeze({
    playerImpact: "CANONICAL_FIE",
    caliber: "CANONICAL_FIE_PLAYER_EVALUATION",
    replacement: "CANONICAL_FIE_PLAYER_AVAILABILITY",
    teamDependency: "CANONICAL_FIE_TEAM_INTELLIGENCE",
    decisionOutput: "CANONICAL_FIE_DECISION_API",
    pickem: "READ_ONLY_CONSUMER",
  }),
  authorizationBoundary: Object.freeze({
    productionAdapterExecutionAuthorized: false,
    playerImpactProductionActivationAuthorized: false,
    teamStrengthMutationAuthorized: false,
    matchupMutationAuthorized: false,
    decisionScoringMutationAuthorized: false,
    pickemScoringMutationAuthorized: false,
    databaseMutationAuthorized: false,
  }),
});
