import {
  buildNFLPerformanceIndexes,
  getNFLTeamPerformanceEvidenceForSeason,
  getNFLTeamPerformanceEvidenceRecordsForSeason,
} from "../../data/footballIntelligence/nfl/performance/NFLTeamPerformanceEvidenceRegistry.js";
import { buildNFLOpponentAdjustment } from "../../data/footballIntelligence/nfl/performance/NFLOpponentAdjustmentEngine.js";

export const NFL_TEAM_STRENGTH_MODEL_VERSION = "NFL-TEAM-STRENGTH-V1.0.0";
export const NFL_TEAM_STRENGTH_PRIOR_VERSION = "NFL-TEAM-STRENGTH-PRIOR-V1.0.0";
const finite=(v)=>typeof v === "number" && Number.isFinite(v);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function weighted(parts){const valid=parts.filter(p=>finite(p?.value)&&finite(p?.weight)&&p.weight>0); if(!valid.length)return null; const tw=valid.reduce((s,p)=>s+p.weight,0); return valid.reduce((s,p)=>s+p.value*p.weight,0)/tw;}
function maturityFor(record){const g=Number(record?.sample?.gamesPlayed)||0; if(g<=0)return{state:"NO_CURRENT_SAMPLE",reliability:0,priorRequired:true}; if(g<=2)return{state:"VERY_EARLY",reliability:.25,priorRequired:true}; if(g<=4)return{state:"EARLY",reliability:.5,priorRequired:true}; if(g<=7)return{state:"DEVELOPING",reliability:.75,priorRequired:true}; return{state:"MATURE",reliability:1,priorRequired:false};}
function seasonBundle(team,season,phaseScope){const record=getNFLTeamPerformanceEvidenceForSeason(team,season,{phaseScope}); if(!record)return null; const peers=getNFLTeamPerformanceEvidenceRecordsForSeason(season,{phaseScope}); const indexes=buildNFLPerformanceIndexes(record,peers); const opponent=buildNFLOpponentAdjustment(peers).get(record.teamAbbreviation)||null; return{record,indexes,opponent};}
function compose(bundle){if(!bundle)return null; const score=weighted([{value:bundle.opponent?.opponentAdjustedIndex??null,weight:.75},{value:bundle.indexes.recentForm,weight:.15},{value:bundle.indexes.specialTeams,weight:.10}]); return score===null?null:clamp(score,0,100);}
export function buildNFLTeamStrength({team,targetSeason,phaseScope="ALL"}={}){const season=Number.isInteger(Number(targetSeason))?Number(targetSeason):new Date().getFullYear(); const current=seasonBundle(team,season,phaseScope); const prior=seasonBundle(team,season-1,phaseScope); const cs=compose(current), ps=compose(prior), maturity=maturityFor(current?.record); let mode="UNAVAILABLE",overallStrength=null,currentWeight=0,priorWeight=0; if(finite(cs)&&maturity.priorRequired&&finite(ps)){mode="BLENDED";currentWeight=maturity.reliability;priorWeight=1-currentWeight;overallStrength=cs*currentWeight+ps*priorWeight;} else if(finite(cs)){mode="CURRENT_ONLY";currentWeight=1;overallStrength=cs;} else if(finite(ps)){mode="PRIOR_ONLY";priorWeight=1;overallStrength=ps;} const confidence=overallStrength===null?null:clamp((mode==="PRIOR_ONLY"?.6:.65+.25*maturity.reliability)+(current?.opponent?.opponentAdjustedIndex!=null?.05:0)+(current?.indexes?.specialTeams!=null?.03:0),0,.95); return{contract:"NFLTeamStrengthResult",version:NFL_TEAM_STRENGTH_MODEL_VERSION,teamAbbreviation:typeof team==="string"?team.trim().toUpperCase():null,targetSeason:season,phaseScope,state:overallStrength===null?"UNKNOWN":"AVAILABLE",overallStrength:overallStrength===null?null:clamp(overallStrength,0,100),confidence,confidenceKnown:finite(confidence),mode,blend:{currentWeight,priorWeight,priorVersion:NFL_TEAM_STRENGTH_PRIOR_VERSION},sampleMaturity:maturity,current:current?{season:current.record.season,gamesPlayed:current.record.sample.gamesPlayed,offenseIndex:current.indexes.offense,defenseIndex:current.indexes.defense,recentFormIndex:current.indexes.recentForm,specialTeamsIndex:current.indexes.specialTeams,opponentAdjustedIndex:current.opponent?.opponentAdjustedIndex??null,strength:cs}:null,prior:prior?{season:prior.record.season,gamesPlayed:prior.record.sample.gamesPlayed,offenseIndex:prior.indexes.offense,defenseIndex:prior.indexes.defense,recentFormIndex:prior.indexes.recentForm,specialTeamsIndex:prior.indexes.specialTeams,opponentAdjustedIndex:prior.opponent?.opponentAdjustedIndex??null,strength:ps}:null,methodology:{seasonStrengthWeights:{opponentAdjusted:.75,recentForm:.15,specialTeams:.10},priorBlend:"sample-maturity reliability blend",calibratedWinProbability:false}};}
export default{NFL_TEAM_STRENGTH_MODEL_VERSION,NFL_TEAM_STRENGTH_PRIOR_VERSION,buildNFLTeamStrength};
